- LICENSE
- README.md
- gatsby-config.js
- package.json
- Clone of setup for ood_online_giving
- End of sprint (Feb 10)
- Med/low
1. TBD
- ADAPT-1483
- @yvonnetangsu @katrialesser 
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)
> Alumni Changes.

- gatsby-config.js
- gatsby-node.js
- package-lock.json
- package.json
- src/components/components.js
- src/components/redirect/Redirect.js
READY FOR REVIEW
- This is a port of work for Redirects made in https://github.com/SU-SWS/ood_giving_site/pull/175
3. Verify...
- Other PRs
- …
> ADAPT-2327: Added possibility to create Redirects

- src/components/cards/basicCard.js
- Image utilities FullWidthImage and CardImage
- both provide image focus and lazy loading options
- FullWidthImage provide srcset and sizes
- CardImage provide several image resizing options (vertical, horizontal, thumbnail), set alt="" for accessibility (it's recommended that screen readers don't read out card images)
- Basic Card component - only vertical orientation; regular (with padding/shadow) and minimal variant
1. Go to https://deploy-preview-19--stanford-alumni.netlify.app/test/yvonne/test-interior-page/
2. Look at 3 basic cards
3. Pull down locally, nvm …
> ADAPT-2328 ADAPT-2064 ADAPT-2380 Basic card component + minimal variant, Image utilities

- package-lock.json
- package.json
- src/components/cards/basicCard.js
- src/components/component_not_found.js
- src/components/composite/hero.js
- src/components/cta/ctaButton.js
- src/components/cta/ctaGroup.js
- src/components/cta/ctaLink.js
- src/components/embed/embed.js
- src/components/identity/localFooter.js
- src/components/identity/localFooterPicker.js
- src/components/layout/grid.js
- src/components/navigation/linkGroup.js
- src/components/navigation/navItem.js
- src/components/page-types/interiorPage.js
- src/components/page.js
- src/components/partials/footer.js
- src/components/partials/header.js
- src/components/partials/htmlHead.js
- src/components/partials/layout.js
- src/components/partials/seo.js
- src/components/redirect/Redirect.js
- src/components/simple/wysiwyg.js
> ADAPT-2116: Suggested Edits.

- src/components/cards/basicCard.js
- src/components/composite/hero.js
- src/components/cta/ctaButton.js
- src/components/cta/ctaLink.js
- src/components/identity/localFooter.js
- src/components/layout/section.js
- src/components/media/fullWidthImage.js
- src/components/navigation/linkGroup.js
- src/components/partials/header.js
- src/utilities/addBgImage.js
- src/utilities/dataSource.js
- Force alt="" in Hero component
- Add heading level selection option for Hero (h1 or h2), for Section (H2 to H6)
- Create `addBgImage `utility for adding a background image to an element, with optional gradient overlay (default to a gradient of top to bottom/transparent to SAA black - which is the most likely case)
- Replace all hover/focus classes with hocus, group-hover/group-focus classes with group-hocus since we have the TW interaction plugin that works with JIT mode.
- Use the TW children variant when appropriate
1. Go to …
> ADAPT-2440 ADAPT-2447 ADAPT-2486: A11y fixes for hero/local footer; allow heading level selection for Section and Hero; addBgImage utility

- package-lock.json
- package.json
- src/components/cards/perkCard.js
- src/components/content-types/perk/perkCardView.js
- src/components/cta/ctaButton.js
- src/components/cta/ctaLink.js
- src/components/identity/localFooter.js
- src/components/simple/tabLabel.js
- src/tailwind/plugins/components/underline/custom-underline.js
- Few tweaks for Perk/Perk Cards
- Thicker underline on card hover
- "new" tab changes from gradient red to solid bright red on card hover
- Headline uses diagonal external icon for external links, and right arrow for internal links
- Headline heading level options is now in Perk Card on Storyblok, not in the Perk content type.
- Use Decanter React v.1.0.0
1. Go to https://deploy-preview-28--stanford-alumni.netlify.app/test/yvonne/test-perks/
2. Check that the "New" tab label changes from gradient red to solid bright red on card hover
3. Check that the headline has …
> ADAPT-2561: Perk Tweaks and use Decanter React v1.0.0

- src/utilities/transformImage.js
- Fixup for a change introduced with the new ESlint config that prevents transformImage from resizing images
1. Go to homepage of preview site
2. Check that the hero image has been processed into different smaller sizes
Like this
- Other PRs
- [AMP …
> ADAPT-000: transformImage fix

- src/components/cards/basicCard.js
- src/components/composite/poster.js
- src/components/content-types/perk/perkCardView.js
- src/components/identity/localFooter.js
- src/components/media/cardImage.js
- src/components/media/circularImage.js
- src/tailwind/plugins/theme/colors.js
- src/utilities/dataSource.js
- Add dark variant for poster, and add foggy-light as light background option
- 3 solid color, 1 solid gradient, and an option to add a background image that will always come with a dark custom gradient overlay
- Add support for really short headline/content for poster with left-aligned content, so that when multiple posters are stacked on top of each other, the position of the round image doesn't shift (the round image should all line up vertically) even if there is very little content on the right.
- Use CircularImage component for Basic Card; Basic Card headline fixup to use Heading component props so classes don't get overriden.
- How critical is this PR on a 1-10 scale? Also see [Severity …
> ADAPT-2658 Dark poster variants

- src/components/layout/section.js
- Add alignment boolean to Sections component
- tbd
2. Review Storyblok config and schema for Section. Confirm that default is center alignment and enabled is left alignment.
- [ADAPT-2568](https://stanfordits.atlassian.net/browse/ADAPT-2568)
> ADAPT-2568 Add alignment boolean to Sections component

- gatsby-config.js
- package-lock.json
- package.json
- src/components/cards/basicCard.js
- src/components/cards/eventCard.js
- src/components/components.js
- src/components/content-types/event/event.js
- src/components/simple/dateBlock.js
- src/components/simple/tabLabel.js
- src/tailwind/plugins/components/underline/custom-underline.js
- Add event content type, vertical and minimal event cards
- Support for both single and multi-day events
1. https://deploy-preview-27--stanford-alumni.netlify.app/test/yvonne/test-events/
2. Look at examples
3. Look at code
- Other PRs
- [AMP …
> ADAPT-2279 ADAPT-2534 Events content type and event cards

- gatsby-node.js
- package-lock.json
- package.json
- src/components/cards/embedCard.js
- src/components/components.js
- Create embedCard
*Unless additional styling is needed, I believe this is ready for review 😄 I'll update Storyblok to include additional variations of embeds on Monday.
- tbd
2. Run local dev or view [Netlify Preview](https://deploy-preview-35--stanford-alumni.netlify.app/test/embed-card-test/)
- [ADAPT-2437](https://stanfordits.atlassian.net/browse/ADAPT-2437)
> ADAPT-2437: Create embedCard

- src/components/cards/basicCard.js
- Change basic card body text field from plain text to rich text, with links enabled
- No support for link colors for light text needed (for minimal cards placed on Sections with black background)
1. https://deploy-preview-43--stanford-alumni.netlify.app/test/yvonne/test-section/
2. Look at the basic cards in the top section, check that the card body links look ok (light digital red link color, on hover/focus cardinal red color)
3. Check that bold and italic work also
4. Check that cards with multiple body paragraphs looks ok too
3. Scroll down to the section with …
> ADAPT-2778: Change Basic Card body text field to rich text

- src/components/content-types/event/event.js
- src/components/content-types/perk/perkCardView.js
- Add backface-visibility:hidden to perk card gradient overlay to prevent flickering
1. https://deploy-preview-45--stanford-alumni.netlify.app/test/yvonne/test-perks/
2. scroll to the grid of vertical perk cards
3. hover over some of the cards and check that there is no strange flickering on the gradient/card image.
- Other PRs
- Anyone who …
> ADAPT-000: Add backface-visibility:hidden to perk card gradient overlay

- gatsby-config.js
- gatsby-node.js
Fixes build errors caused by no content of type.
RE: https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#fixing-field-types
> ADAPT-000: GraphQL Build errors (#39)

- gatsby-config.js
- Encountered a Gatsby #10123 Config error since the "version:" was missing. This PR adds "version:" back to to gatsby-source-storyblok config.
- asap?
3. Verify...
- Other PRs
- …
> ADAPT-000 Add "version:" for gatsby-source-storyblok

- package.json
- src/components/components.js
- src/components/media/embedVideo.js
- src/utilities/dataSource.js
- Add Rich Media Component
- July 6
1. Check out branch
2. Run local dev and review `test/rebecca/rich-media-test` or [Netlify Preview](https://deploy-preview-53--stanford-alumni.netlify.app/test/rebecca/rich-media-test/)
- [ADAPT-2734](https://stanfordits.atlassian.net/browse/ADAPT-2734)
> ADAPT-2734 Add Rich Media Component

- src/utilities/dataSource.js
- Add mobile button padding
- tbd
2. Run local dev and review on mobile screen width at `test/rebecca/mobile-button-test` or [Netlify preview](https://deploy-preview-57--stanford-alumni.netlify.app/test/rebecca/mobile-button-test/)
- [ADAPT-2661](https://stanfordits.atlassian.net/browse/ADAPT-2661)
> ADAPT-2661 Add mobile button padding

- gatsby-config.js
- src/components/cards/basicCard.js
- src/components/cards/storyCard.js
- src/components/components.js
- src/components/composite/hero.js
- src/components/content-types/event/event.js
- src/components/content-types/story/story.js
- src/components/content-types/story/storyCardView.js
- src/components/content-types/story/storyPageView.js
- src/components/layout/grid.js
- src/components/layout/section.js
- src/components/page-types/darkPage.js
- src/tailwind/plugins/theme/colors.js
- Story Card (vertical) with minimal variant
- Options for: big text (title and teaser), minimal, hide image (will also hide tab automatically), hide tab only, heading level, image focus
- Note: Waiting for Story Card media icon (for podcast/video) in mockup - will add this in a later PR.
- Note2: no need to review the storyPageView.js code for now - work will be continued in another PR for story page.
1. https://deploy-preview-63--stanford-alumni.netlify.app/test/yvonne/test-story-cards/
2. Look at all the options
3. Pull down locally and go to Text Event page on …
> ADAPT-2918: Story Card

- src/components/composite/hero.js
- src/components/composite/poster.js
- src/components/content-types/event/event.js
- src/components/content-types/perk/perkCardView.js
- src/components/cta/ctaButton.js
- src/components/layout/section.js
- src/components/navigation/mainMenuGroup.js
- src/components/simple/tabLabel.js
- A11y fixes suggested by SODA
1. Looked at the comments where I called out each change and see if code does what I claim.
- Other PRs …
> ADAPT-2903: Accessibility fixes

- package-lock.json
- package.json
- src/components/layout/modal.js
- src/components/search/openSearchModalButton.js
- src/components/search/searchFieldModal.js
- src/components/search/searchModal.js
- src/hooks/useFocusTrap.js
This is the first part of the search modal implementation it:
- Adds open/close functionality on the Search button in the header. 
- Provides a modal component with accessibility considerations, like close-on-escape, auto-focus on search input, and focus-trapping.
- Preferably 1-2 days, as other tickets this sprint will build on the work in this PR.
- How critical is this PR on a 1-10 scale?
7/10 - This is a fairly critical piece of functionality for the site, that appears on the sitewide header. 
2. Go to any page that has the sitewide header added. (For example: http://localhost:8000/test/yvonne/test-dark-page)
3. Click the "Search" button in the header. 
4. Confirm that the modal is opened.
5. Confirm that focus trap works as expected.
6. Confirm that …
> ADAPT-2880: Search Modal open/close behavior

- src/components/media/simpleImage.js
- src/utilities/dataSource.js
- Add spacing options and full viewport style
- July 7
3. Verify...
- [ADAPT-2932](https://stanfordits.atlassian.net/browse/ADAPT-2932)
> ADAPT-2932 Add spacing options and full viewport style

- gatsby-config.js
- Update gatsby-config version ternary from the process.env to activeEnv 
- tbd
3. Verify...
- Other PRs
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack …
> ADAPT-000: Update gatsby-config version ternary

- package-lock.json
- package.json
- src/components/cards/iconCard.js
- src/components/components.js
- src/components/content-types/event/event.js
- src/components/content-types/story/storyCardView.js
- src/components/content-types/story/storyPageView.js
- src/components/page-types/basicPage.js
- src/components/page-types/darkPage.js
- src/components/partials/ankle.js
- src/components/partials/basicContentLeftSidebar.js
- src/components/partials/htmlHead.js
- src/components/simple/wysiwyg.js
- src/styles/global.css
- src/utilities/dataSource.js
- Icon cards - light and dark theme
- Ankle region in Basic Page, Dark Background Page and Story Page
- On the Dark Background Page, there is no background color choice for ankle. It will automatically use the black background and the dark themed icon cards.
1. 3 icon cards, basic page:
https://deploy-preview-73--stanford-alumni.netlify.app/test/yvonne/test-basic-page-interior-hero/
2. 3 icon cards, dark page:
https://deploy-preview-73--stanford-alumni.netlify.app/test/yvonne/test-dark-page/
3. 2 icon cards on story page: …
> ADAPT 2900, ADAPT-2738: Icon card and ankle region

- gatsby-config.js
- gatsby-node.js
- src/components/partials/seo.js
- src/templates/storyblok-entry.js
- Add canonical url to SEO
- July 13
2. [Netlify Test Preview](https://deploy-preview-71--stanford-alumni.netlify.app/test/rebecca/url-test)
- [ADAPT-2851](https://stanfordits.atlassian.net/browse/ADAPT-2851)
- [Browserstack](https://live.browserstack.com/dashboard) and link to …
> ADAPT-2851: Add canonical url to SEO

- lambda/config/indexMedia.config.js
- lambda/indexMedia.js
- package-lock.json
- package.json
- This adds the Soundcloud podcast feeds to the mediaIndexing script.
- This PR does **not** add the media results to the search page yet, or merge the media results into the same index as the crawler results. 
- Next 1-3 days. 
- 8/10 - This feature is part of the MVP expected to be delivered on July 28th.
1.  Visit /api/indexMedia?key=LAMBDA_SECRET on the preview environment. (You can find the LAMBDA_SECRET in the netlify environment variables).
2. After the function completes, look at the media index in alogolia and validate that the results are present: https://www.algolia.com/apps/IC2GX4TRIN/explorer/browse/alumni_media?searchMode=search
- https://stanfordits.atlassian.net/browse/ADAPT-2835
> ADAPT-2835: Soundcloud Indexing

- src/components/navigation/mainMenuGroup.js
- Remove HeadlessUI Popover and Transition components from the main nav (parent item buttons and dropdown menus)
- Main Nav should function as before keeping all click and keyboard behaviors - space bar + enter to open/close dropdowns, click outside and use escape key to close, tabbing
- Note: Keeping HeadlessUI dependency for now since we have a ticket for Elena to explore the List Box component for filtering.
1. https://deploy-preview-78--stanford-alumni.netlify.app/test/yvonne/test-basic-page-interior-hero/
2. Check main nav functionality on desktop, then on …
> ADAPT-2988: Remove HeadlessUI Popover component from main nav

- package-lock.json
- src/components/components.js
- src/components/identity/masthead.js
- src/components/layout/modal.js
- src/components/page-types/searchPage.js
- src/components/search/openSearchModalButton.js
- src/components/search/searchAutocomplete.js
- src/components/search/searchField.js
- src/components/search/searchFieldModal.js
- src/components/search/searchModal.js
- src/components/search/searchSuggestions.js
- src/components/simple/linkList.js
- Adds search functionality and suggestions content to search modal. 
- Next 2-3 days. 
- 8/10 - This functionality is expected to be part of the MVP delivered on July 28th.
1. Go to a page with the global header, such as: http://localhost:8000/test/yvonne/test-dark-page/
2. Click the Search button in the header.
3. Try out the search field, and validate that the autocomplete and submit functionality behaves as expected.
4. Validate that the "Consider Browsing by Category" content is presented and behave as expected.
Note that the content for this can be edited under Global Components -> Search Modal -> Search Suggestions.
(I refactored the no results content to use the same components, but the content for the two places is independent)
- …
> ADAPT-2665: Search modal functionality and content

- netlify.toml
> ADAPT-000: Block robot from indexing

- google3bfc006a07428fd8.html
> google-verify-code

- src/components/page-types/searchPage.js
> ADAPT-3011: Add above and below content to search results page

- src/components/page-types/searchPage.js
- src/components/partials/htmlHead.js
- src/components/search/searchField.js
- src/components/search/searchFieldModal.js
- src/components/simple/linkList.js
- Fixes bug where clicking the clear button in the search field closed the modal.
- Next 1-3 days.
- 7/10 - Search modal is a key piece of the MVP, and the un-fixed behavior is confusing.
1. Go to a page with the global header, like /test/yvonne/test-dark-page/
2. Click the search button in the header.
3. Click the clear button, validate that it clears text from input as expected, but does not close the modal.
4. Also check /search and validate that the clear behavior here still works as expected. (i.e. clears text from modal, and resets search results).
- https://stanfordits.atlassian.net/browse/ADAPT-3017 …
> ADAPT-3017: Bug fix, for clear button closing modal.

- src/components/page-types/searchPage.js
- src/components/search/searchField.js
- src/components/search/searchFieldModal.js
> ADAPT-2669: Adjust spacings for search input

- src/components/media/embedVideo.js
- Update Embed component caption with CaptionMedia
2. Review locally at `test/rebecca/embed-caption-test` or [Netlify Preview](https://deploy-preview-94--stanford-alumni.netlify.app/test/rebecca/embed-caption-test/)
- [ADAPT-3057](https://stanfordits.atlassian.net/browse/ADAPT-3057)
- …
> ADAPT-3057 Update Embed component caption to use the CaptionMedia

- src/components/page-types/searchPage.js
- src/components/search/searchFacet.js
- src/components/search/searchResults.js
- Adds icons for video and podcast items.
- Adds icons for internal/external link indicators.
- Adds additional filter for audio/video types.
- Next 1-2 days. 
- 8/10 - Part of search MVP due by the 28th. 
1. Go to /search. 
2. Validate that youtube, soundcloud and itunes podcast items appear and have appropriate styling. (ie. video icon for youtube, microphone icon for itunes/soundcloud.)
3. Validate that the new Media type filter appears, and works as expected.
- https://stanfordits.atlassian.net/browse/ADAPT-3006
> ADAPT-3006: Media search result adjustments

- src/components/layout/widthBox.js
- src/components/media/captionMedia.js
- src/components/media/simpleImage.js
- src/utilities/dataSource.js
- Refactor SimpleImage component to use transformImage and captionMedia components
2. View authoring experience on [StoryBlok](http://app.storyblok.com/#!/me/spaces/103430/stories/0/0/57163206/blok/a4b1067b-e68f-46fa-b300-47fda1dc1f56?s=1)
3. Review locally at `test/rebecca/simple-image-test` or see [Netlify Preview](https://deploy-preview-97--stanford-alumni.netlify.app/test/rebecca/simple-image-test/)
- [ADAPT-3060](https://stanfordits.atlassian.net/browse/ADAPT-3060)
- …
> ADAPT-3060 Refactor SimpleImage component to use transformImage and captionMedia components

- src/components/search/searchFacet.js
- Add decanter class names back to form elements
3. Verify...
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEP …
> ADAPT-000: Put back in decanter form classnames

- src/utilities/transformImage.js
- Remove the isNetlify check in utility transformImage.js, so that the storyblok image service filters work in dev mode.
1. Check out this branch, nvm use, npm run develop
2. go to any page in SAA storyblok with image
3. Check that the images have been processed through storyblok image service filters
4. Go to https://deploy-preview-101--stanford-alumni.netlify.app/test/yvonne/test-basic-page-interior-no-hero/
5. Verify that the images in the netlify build work the same as before.
- …
> ADAPT-3028: Remove isNetlify check in transform image

- src/components/search/searchFieldModal.js
- UI Fix for search modal.
- Next 2-3 days.
- 5/10. Small UI enhancement
1. Visit /search (or another page with the global header).
2. Click the search button in the header.
3. Verify that the magnifying glass icon in the search button has been flipped, so that the handle now faces right instead of left.
- https://stanfordits.atlassian.net/browse/ADAPT-2665?focusedCommentId=113247
> ADAPT-2665: Flip direction of search icon.

- src/components/composite/hero.js
- src/components/navigation/mainMenuGroup.js
- src/components/navigation/mainNav.js
- Fixup hamburger main nav button hover/focus state inherited from pulling in a newer version of Decanter. Button on hocus should only get border on the bottom and not all around.
- Fixup mobile main nav - when hover over parent items, there should be an underline on the text.
- For desktop, main nav top level parent items text on hover should be color digital-red-xlight.
- Make Hero headline on mobile all go to modular-type 4 (su-text-m4) no matter what the headline size option is selected.
1. Go to …
> ADAPT-3104, ADAPT-3090: Fixup for main nav hamburger button hover/focus state and desktop parent item; hero headline mobile font size

- src/components/layout/grid.js
- Requested by Kerri - reduce the vertical Grid component gutter by about 1/3
- Note: This has passed visual QA with Kerri
1. Look at example pages and check vertical grid gutter on all breakpoints and see that they have been reduced. Note: This has passed visual QA with Kerri
2. https://deploy-preview-105--stanford-alumni.netlify.app/perks/
3. https://deploy-preview-105--stanford-alumni.netlify.app/test/yvonne/test-dark-page/
4. https://deploy-preview-105--stanford-alumni.netlify.app/about/contact/ (Don't worry about the darker basic card border - working on tweaks …
> ADAPT-3107: Reduce vertical gutter of Grid component

- src/components/page-types/searchPage.js
- Added spacing between filters and content on search page
3. Verify the space between the filters and results
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCj …
> ADAPT-3108: Added spacing between filters and content on search page

- src/components/page-types/searchPage.js
- src/components/search/searchFieldModal.js
- Changed the font weight for thee search input
3. Verify search input on the page and modal
- Other PRs …
> ADAPT-3122: Remove fw semibold for the search input

- src/components/page-types/searchPage.js
- Fixed: On the search page - when there is a featured search results banner, e.g, one that uses the horizontal perk card, if someone types in the search input, the autocomplete dropdown is covered up by the feature banner 
3. Verify that the search suggestions dropdown doesn't hide behind the featured banner
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new …
> ADAPT-3132: Change search field container zindex

- src/components/page-types/searchPage.js
- Rotate the red icon on the search page
3. Verify that the red search icon is oriented the same way as the header search icon
- Other PRs …
> ADAPT-3112: Rotate search icon

- src/components/simple/wysiwyg.js
- Added an option to the wysiwyg component that will add left or centered text class 
- 1
2. Navigate to help/stanfordpass 
3. Verify that text is centered now
- Other PRs
- …
> ADAPT-3092: Wysiwyg center text option

- src/components/layout/grid.js
- src/components/layout/section.js
- Add option for wider grid horizontal grid gaps for the Grid component (content author can select when placing minimal cards so they don't appear so close together; remove previous "removeGap" prop and consolidate it with the "gapWidth" prop/option.
- Add option for medium Section title font size (in between default/large and the small option)
- Note: This has passed visual QA with Kerri
Note: This has passed visual QA with Kerri
1. Go to https://deploy-preview-106--stanford-alumni.netlify.app/resources/learn/
2. scroll down to the minimal event card section …
> ADAPT-3107: Large grid gap option, Section title font size option

- src/components/search/searchFacet.js
- Change cursor for search checkboxes to pointer
3. Verify that the ckecboxes have pointer cursor on hover
- Other PRs …
> ADAPT-3117: Change cursor for search checkboxes

- src/components/cards/ctaCard.js
- src/components/cards/iconCard.js
- Remove internal link icon (right arrow) on Icon Card headlines when it's an internal link. Request from Michele.
1. Go to https://deploy-preview-115--stanford-alumni.netlify.app/test/yvonne/test-dark-page/
2. Scroll down to the ankle and look at the card "Contact us...."
3. Check that there is no right arrow icon on the headline
4. Check the card to the left of it, and see that the external link icon is still there when the link is external.
- …
> ADAPT-3152: Remove internal link icon for icon cards

- src/components/search/searchResults.js
- Media icons position on the search results
2. Navigate to /search?type=video&type=audio
3. Check media icons 
- Other PRs …
> ADAPT-3121: Search media icons position 

- src/components/page-types/searchPage.js
- Updates styling of autocomplete on primary search page to match version in search modal. 
1. Go to /search
2. Validate the styles for the autocomplete container matches the autocomplete in the search modal.
- https://stanfordits.atlassian.net/browse/ADAPT-3114
> ADAPT-3114: Updated autocomplete styling to match modal version.

- src/components/search/searchFieldModal.js
- src/components/search/searchModal.js
- Added a helper text for when the search input in submitted empty.
1. Navigate to https://deploy-preview-91--stanford-alumni.netlify.app/search/
2. Check out the functionality on the search modal
- Other PRs
- [Accessibility …
> ADAPT-2728: Replacing intro text with emptySearchText if input empty

- src/components/page-types/searchPage.js
- Removes blue focus outline on search input.
- Within the next week. 
- 3/10 - The outline is a bit of an eyesore, but doesn't affect functionality.
1. Visit /search
2. Start typing into the search input. Validate that the blue focus outline is no longer present.
- https://stanfordits.atlassian.net/browse/ADAPT-3120
> ADAPT-3120: Removed outline from search field.

- src/components/cards/eventCard.js
- src/components/content-types/event/event.js
- src/components/content-types/perk/perkCardView.js
- src/components/content-types/story/storyCardView.js
- src/components/simple/dateBlock.js
- src/components/simple/tabLabel.js
- Misc card tweaks (called out below)
1. See event cards https://deploy-preview-122--stanford-alumni.netlify.app/test/yvonne/test-events/
2. For the non minimal cards, hover or tab to a card, the shadow should deepen. The tab label should change to a brighter red and the image zoom will happen when kayboard focused (matches hover state).
3. Scroll down to the bottom dark minimal cards - check that it looks ok.
4. Check that all the event detail icons look ok (the calendar, map pin/computer and organizer icons).
5. See story cards …
> ADAPT-2989: More card tweaks

- src/components/search/searchModal.js
- Changes the graphql lookup from ID to full slug and protects variables
- Builds were failing on dev when I used the CLI tool to sync content back down stream and the UUIDs changed
- Whenever
- Low
1. Review code
2. Review preview build to see that modal content still appears
3. Pull down branch to local
4. Rebuild on local with API key set to DEV storyblok space
5. Validate that the content in the modal still appears
6. Change the graphql query so it fails
7. Rebuild local environment
8. Validate build still works and page renders but content is missing
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, …
> ADAPT-000: Change static graphql query from ID to slug for multi environment.

- src/components/layout/modal.js
- src/components/search/searchFacet.js
- src/components/search/searchModal.js
Added scroll to the search modal
3. Verify...
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=shari …
> ADAPT-3117: Scrollable modal

- src/components/search/searchResults.js
- Added external/internal icons and hover state to search result titles. The internal link icons won't appear on non prod env https://ffwagency.slack.com/archives/C01RS7TSGPN/p1628705158054500?thread_ts=1628703685.052600&cid=C01RS7TSGPN
3. Verify hover states of the search results titles
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, …
> ADAPT-3118: Add underline and correct icons

- package-lock.json
- package.json
- src/components/composite/poster.js
- src/components/layout/section.js
- src/components/page-types/searchPage.js
- src/components/partials/layout.js
- src/components/simple/wysiwyg.js
- Remove package react-id-generator
- Remove usage of it in WYSIWYG, Section and Poster components
- Add main-content id to search page for skiplink
2. Go to https://deploy-preview-125--stanford-alumni.netlify.app/search/
3. After the page load, immediately hit tab key on the keyboard, the skiplink should come up. If you click on the skiplink, it should skip pass the masthead and goes to the content header with the page title "Search for..." 
- Other PRs
- Any other …
> ADAPT-3157: Remove package react-id-generator and its usage

- gatsby-config.js
- gatsby-node.js
- src/components/page-types/basicPage.js
- Adds `<meta name="robots" content="noindex">` when noIndex field is checked in Storyblok.
- Excludes page from XML sitemap when noIndex flag is checked. 
- By end of sprint. 
Probably 7/10? 
It will be important to exclude certain pages from the search index. But this isn't an urgent/site breaking sisue.
1. Checkout this branch on your local.
2. Create a test Basic Page on Storyblok. Check the "no index" checkbox in the "SEO & Social" tab.
3. Visit the page in the browser on your localhost environment. Check the page markup in dev tools - validate that you see `<meta name="robots" content="noidex">` in the head section. 
4. View other pages that do not have …
> ADAPT-3106: Added code to support no-index parameter in page metatags and sitemap.

- src/components/search/searchResults.js
- Fixed the search results image aspect ratio. 
3. Verify mobile and desktop search result aspect ratio
- Other PRs …
> ADAPT-3141: Fix search results image aspct ratio

- src/components/composite/alert.js
- src/styles/alert.css
- Adjust alert link colors
- Aug 17
2. Review locally at `test/rebecca/aug-12-bug-scrum` or Netlify preview
Check the hover and focus state of the Alerts. Confirm that they match the mockup:
- [ADAPT-3185](https://stanfordits.atlassian.net/browse/ADAPT-3185)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)
> ADAPT-3185 Adjust alert link colors

- src/components/media/simpleImage.js
- Update SimpleImage component to use FullWidthImage component for edge-to-edge
- Aug 17
2. Review locally at `test/rebecca/simple-image-test` or on [Netlify preview](https://deploy-preview-130--stanford-alumni.netlify.app/test/rebecca/simple-image-test/)
Confirm that the image focus still works as intent for banners and that none of the images have changed.
- [ADAPT-3156](https://stanfordits.atlassian.net/browse/ADAPT-3156)
- …
> ADAPT-3156 Update SimpleImage component to use FullWidthImage component for edge-to-edge

- src/components/search/searchResults.js
- Fix encoding bug for the search results title
3. Filter by video and check the titles 
- Other PRs …
> ADAPT-3187: Fix title encoding issue for search results

- src/components/identity/masthead.js
- src/components/navigation/mainMenuGroup.js
- src/components/navigation/verticalNav.js
- src/components/page-types/basicPage.js
- src/components/partials/basicContentLeftSidebar.js
- src/components/partials/header.js
- Added a second skiplink to the main menu
2. Navigate to any page
3. Verify the skiplink
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqM …
> ADAPT-2945: Add skiplink to section menu

- src/components/search/searchPager.js
- src/utilities/buildPager.js
- Provides alternate pager appearance and behavior for mobile screen sizes.
3. Verify...
- https://stanfordits.atlassian.net/browse/ADAPT-2670
- [Browserstack](https://live.browserstack.com/dashboard) and link to …
> ADAPT-2670: Created alternative pager for mobile.

- src/components/cta/ctaLink.js
- src/components/page-types/searchPage.js
- src/components/search/searchKeywordBanner.js
- src/components/search/searchResults.js
- Fix grid layout for search page and when there is no search results
- Add bottom spacing to keyword search feature banner
- CTA link color fixup
1. Go to https://deploy-preview-135--stanford-alumni.netlify.app/search/
2. Check that left side of the search input bar, and the search content region (the left side of the number of results text) should align, currently they're not on the live site.
3. Go to https://deploy-preview-135--stanford-alumni.netlify.app/search/?q=bbbbbbbbb
4. Check that the search bar and the content region both span 8 of 12 columns and are …
> ADAPT-3167: Add bottom spacing to keyword search banner; CTA link color transition; search page grid

- src/components/cta/ctaLink.js
- src/utilities/dataSource.js
1. Go to https://deploy-preview-141--stanford-alumni.netlify.app/
2. Scroll to local footer, check that the CTA links have digital red xlight arrow icons and hovers to white (black 20%)
3. Go to https://deploy-preview-141--stanford-alumni.netlify.app/test/poster-test/
4. Scroll to the bottom 3 posters, check that the CTA link icon on the foggy light posters is digital red xlight hovers to cardinal red; in the black poster, the icon is digital red xlight hovers to white (black 20%), and in the last …
> ADAPT-000: Fixup CTA Link icon color

- src/components/layout/modal.js
- src/components/page-types/searchPage.js
- src/components/search/searchField.js
- src/components/search/searchFieldModal.js
- src/components/search/searchModal.js
- src/components/search/searchNoResults.js
- src/components/search/searchSuggestions.js
- src/components/simple/linkList.js
- Search modal style and empty search message handling changes
- Remove dynamic classnames since Tailwind doesn't like that
- Search page submit search button tweaks
NOTE: This has passed visual QA with Kerri 😄 
1. Go to https://deploy-preview-143--stanford-alumni.netlify.app/search/?q=awards
2. Click the "Search" button in the masthead to open up the search modal
3. Check all breakpoints and see that spacing looks ok.
4. Try hitting the magnifying glass icon without entering anything in the search input. Check that the empty search message display below the search …
> ADAPT-3143: Search modal styles

- src/components/cards/basicCard.js
- Fixup for non-minimal card placed in dark sections
1. Go to https://deploy-preview-144--stanford-alumni.netlify.app/resources/learn/
2. Scroll down to this section:
3. Verify that the basic cards have white backgrounds (currently on live, they don't - compare https://alumni-preview.stanford.edu/resources/learn/)
- Other PRs
- Anyone who …
> ADAPT-000: Basic Card fixup

- src/components/search/searchField.js
- Removes auto-focus behavior on search autocomplete, so that search will be submitted with user-entered text on submit rather than the first autocomplete suggestion. 
- Next 1-2 days. 
- High priority
1. Open the search modal by clicking the search button in the header.
2. Attempt to type a search query in hit enter. 
3. Validate that your search text is carried over to the search results as entered. (Previously, the first autocomplete item was getting auto-focused and submitted as the search query). 
4. Validate this same behavior is working on /search as well. 
- https://stanfordits.atlassian.net/browse/ADAPT-3222
> ADAPT-3222: Remove autoselect behavior on search suggestions.

- src/components/layout/grid.js
- Grid component fixup for LG breakpoint
1. Go to https://deploy-preview-147--stanford-alumni.netlify.app/about/people/
2. Look at horizontal (minimal) basic cards with round thumbnails under "Executive leadership"
3. Check that at LG breakpoint (eg, 1000px screen width), the horizontal cards stays 1 card per row like this instead of 2 per row
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that …
> ADAPT-000: hotfix | Grid fixup

- src/components/composite/hero.js
- Add option to hide "scroll to explore" link on hero banner
- This is a feature request from SAA homesite client, but will also be used for Travel/Study
1. Go to https://deploy-preview-152--stanford-alumni.netlify.app/test/yvonne/test-basic-page-interior-hero/
2. See there no "scroll to explore" link on the hero banner is being rendered
3. Check every breakpoint to see that things look good still.
4. Go to https://deploy-preview-152--stanford-alumni.netlify.app/
5. Check that the "scroll to explore" link is still there and that it looks the same as production.
- …
> ADAPT-3209: Add option to hide "scroll to explore" link on hero banner

- netlify.toml
- Adds x-frame-options header to prevent site from being embedded on other sites.
3. Verify...
- Other PRs …
> ADAPT-3305: Add x-frame-options headers.

- gatsby-node.js
- package-lock.json
- package.json
- src/components/components.js
- src/components/page-types/TripPage.jsx
- src/components/search/openSearchModalButton.js
- Fixed bug with gatsby creating pages for global components
- Fixed bug with invalid classname property
- Basic trip page layout component.
Just left this basic while I exploring existing components in sb and react. Assuming the additional tickets will fill it out.
3. Verify...
> ADAPT-3255 | trip page layout

- tailwind.config.js
- Removes cache directories from tailwind scans. 
- Probably contributing to the memory errors
- Picking up things it shouldn't scan "Like font awesome SVGs"
- Blame Shea for leaving these around for when I was investigating a post build tailwind purge
- Whenever
- Low
> ADAPT-000: Update tailwind.config.js

- src/components/cards/embedCard.js
- Resolve Embed Card issue that Forest reported in [slack](https://stanfordwebservices.slack.com/archives/C01C0BV6FQA/p1631641299063900)
- asap
1. Pull this PR
2. Review Locally at `test/embed-card-test` or [Netlify Preview](https://deploy-preview-165--stanford-alumni.netlify.app/test/embed-card-test)
3. Review the Tockify embed and confirm that it still works as expected with and without neighboring cards. It should span full width of the container (within the confines of the Grid component)
- @buttonwillowsix 
- [AMP …
> ADAPT-000 Embed Card Width Fixup

- src/components/composite/hero.js
- src/components/cta/ctaLink.js
- src/components/identity/localFooter.js
- src/components/page-types/searchPage.js
- src/components/partials/header.js
- src/components/search/searchField.js
- src/components/search/searchFieldModal.js
- src/components/search/searchModal.js
- src/components/search/searchResults.js
- src/components/simple/linkList.js
- Several a11y search improvements
- Individual items called out below
1. Please look at all things called out below
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjm …
> ADAPT-3715: Misc search a11y fixes

- src/components/page-types/searchPage.js
- Fixes conflicting state sources for search query params
- ASAP
1.  Navigate to https://deploy-preview-175--stanford-alumni.netlify.app/search/
3. Verify that clicking pagination links work as expected
4. Enter search query in search page input and ensure pagination links work as expected
5. Enter search query in search modal input (from masthead search)  and ensure pagination links work as expected
6. Use sidebar filters and ensure pagination links work as expected
> ADAPT-3736 | @mattanglin | fix search pagination

- src/components/content-types/story/storyCardView.js
- Fix issues where story card content background color doesn't fill the border when card are forced to take on same height (in the Grid option)
- I also checked the other cards and it appears that only Story Card has this issue
Screenshot of issue:
- ASAP before code freeze
- 9/10
1. https://deploy-preview-176--stanford-alumni.netlify.app/stories/
2. Scroll to the bottom to the "All about alums" section.
3. Check that the white card background now fills the border
- Other PRs
- [AMP …
> ADAPT-3741: Make card content background color fill the border

- src/components/composite/poster.js
- src/components/identity/masthead.js
- src/tailwind/plugins/theme/screens.js
- tailwind.config.js
- Client added an extra word "Check" before "Email" in utility nav which causes it to wrap to 2nd line for devices below 375px. This PR makes it not wrap to 2nd line for 360 to 374px devices (360px is the smallest we'll support)
- Add an extra XS breakpoint at 375px
- Fix poster thumbnail so it's always circular at all breakpoint
- ASAP
- 9/10
1. Go to https://deploy-preview-178--stanford-alumni.netlify.app/
2. Bring up the inspector, and choose the "Galaxy S5" device which is 360px wide
3. Check that the utility (top) nav is all on one line
4. Check the poster under the hero at all breakpoint and make sure that the image is circular for all breakpoints
- Other PRs
- Any other contextual information that …
> ADAPT-3742: Adjust utility nav so it doesn't wrap to 2nd line for 360-374px devices

- src/components/cards/perkCard.js
- src/components/composite/poster.js
- src/components/content-types/event/event.js
- src/components/content-types/perk/perkCardView.js
- src/components/content-types/story/storyCardView.js
- src/components/layout/modal.js
- src/components/page-types/searchPage.js
- src/components/search/searchFieldModal.js
- Misc fixups and improvements before SAA Homesite launch
- Add support for vertical perk cards when placed in light sections
- 8/10
1. Go to https://deploy-preview-177--stanford-alumni.netlify.app/membership/
2. Look at the vertical perk cards and check that they don't have the ugly dark borders like on live
Good:
Bad:
https://alumni-preview.stanford.edu/membership/
3. Go to https://deploy-preview-177--stanford-alumni.netlify.app/perks/
4. Check that the vertical perk cards placed inside the dark sections still look nice.
5. Look at things called out below.
- Other PRs
- Any other contextual information that might be helpful …
> ADAPT-000: Misc fixes

- gatsby-browser.js
- src/components/composite/TripFilterList/TripFilterList.jsx
- src/components/composite/TripFilterList/TripFilterList.styles.js
- src/components/page-types/TripFilterPage/TripFilterPage.jsx
- src/components/page-types/TripFilterPage/TripFilterPage.styles.js
- src/components/simple/FilterCheckbox/FilterCheckbox.jsx
- src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
- src/hooks/useTripFilters.js
- src/utilities/filterTrips.js
- Trip filters side nav desktop styles
1. Navigate to https://deploy-preview-179--stanford-alumni-uat.netlify.app/travel-study/destinations/
3. Verify filter sidebar desktop styles
> ADAPT-3274 | @mattanglin | trip filters sidebar

- src/components/content-types/story/storyPageView.js
- src/components/page-types/basicPage.js
- src/components/page-types/darkPage.js
- src/components/partials/ankle.js
- src/components/partials/ankle/ankle.jsx
- src/components/partials/ankle/ankleStyles.js
- tailwind.config.js
- Add intro (richtext) to ankle region
- Refactor ankle.js to separate out styles
- before end of this sprint
- 6/10
Note: Had some comms with Bhavika and Kerri and they would like to tighten up the spacing between ankle title and intro compared to the current mockup. This PR has taken into account that change which makes the netlify preview slightly different from the Figma mocks. Also, going with the icon card width in SAA Homesite when there are only 2 cards, so that's also slightly different from the mockup.
1. Go to https://deploy-preview-184--stanford-alumni-uat.netlify.app/travel-study/curated-collections/
2. This page uses the `Dark Background Page` type. Look at the ankle and check that an intro could be added below the heading
3. Go to …
> ADAPT-3702: Add intro to ankle region

- src/utilities/filterTrips.js
- Updates trip filtering for multi-option regions
1. Navigate to https://deploy-preview-188--stanford-alumni-uat.netlify.app/travel-study/destinations/
2. Verify that the **Costa Rica, Panama and Colombia** trip can filter into both "Central America" and " South America" filters
3. Verify other filters work as expected
> ADAPT-3768 | @mattanglin | multi-option region trips

- src/components/page-types/TripPage/TripPage.jsx
- src/components/page-types/TripPage/TripPageItinerarySection.jsx
- src/components/page-types/TripPage/TripPageItinerarySection.styles.js
- src/components/page-types/TripPage/TripPageSectionWrapper.styles.js
This PR is based off of #195 and thus it includes the changeset from that PR as well. This PR will be rebased once #195 has been merged into `dev`.
- Trip Page Itinerary Section
- end of sprint
1. Navigate to https://deploy-preview-197--stanford-alumni-uat.netlify.app/travel-study/trips/botswana-south-africa-and-zambia/#trip-itinerary-section
3. Verify styling and display of itinerary section
> ADAPT-3297 | @mattanglin | trip page itinerary section

- src/components/navigation/SAAMainNav/SAAMainNav.styles.js
- src/components/page-types/TripFilterPage/TripFilterPage.jsx
- src/components/page-types/TripPage/TripPage.jsx
- Add ankle region to trip filter and trip detail pages
1. https://deploy-preview-199--stanford-alumni-uat.netlify.app/travel-study/destinations/
2. https://deploy-preview-199--stanford-alumni-uat.netlify.app/travel-study/trips/botswana-south-africa-and-zambia/
2. Scroll to right above the local footer and check that the ankle region show up correctly
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new …
> ADAPT-3283: Add ankle to trip filter and trip detail pages

- static/google83a00cb6501cf923.html
- Verification file for Google Search Console
- I left the old one since that might also be needed for something I am unaware of
No rush
Medium. It would be nice if Google re-indexed
1. Log onto Google Search Console as swsdevelopers@gmail.com
2. Verify site
- Other PRs
- …
> ADAPT-2943: Google Search Console verification

- src/components/cards/TripCard/TripCard.jsx
- src/components/cards/TripCard/TripCard.styles.js
- src/components/composite/HeroImage/HeroImage.jsx
- src/components/composite/HeroImage/HeroImage.styles.js
- src/components/composite/Pagination/Pagination.styles.js
- src/components/composite/TripFilterList/TripFilterList.styles.js
- src/components/identity/global-header/GlobalHeader.jsx
- src/components/media/fullWidthImage.js
- src/components/navigation/SAAMainNav/SAAMainMenuGroup.jsx
- src/components/navigation/SAAMainNav/SAAMainNav.jsx
- src/components/navigation/UtilityNav.jsx
- src/components/navigation/mainMenuGroup.js
- src/components/page-types/TripFilterPage/TripFilterPage.jsx
- src/components/page-types/TripFilterPage/TripFilterPage.styles.js
- src/components/page-types/TripPage/TripPageHeroSection.styles.js
- src/components/simple/Chip/Chip.styles.js
- src/components/simple/Date/Date.jsx
- src/components/simple/Date/Date.styles.js
- src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
- src/tailwind/plugins/theme/colors.js
- src/utilities/convertAspectRatio.js
- Responsive styles and finetuning for Trip Filter page, Trip Card, HeroImage
- Add title (render as H1), intro, heroImage schema to Trip Filter page, remove the hero and aboveContent regions in Trip Filter page (will remove schemas on Storyblok after this PR is merged)
- Add support for image with fixed aspect ratio to fullWidthImage so the focal point can be used properly.
Note:
Added some responsive behavior for filter page for things to fit better, but will need to finetune later after Bhavika updates responsive styles, e.g, I need to fit things properly for LG breakpoint so that's what it looks like for now
)
- 6/10
1. Go to https://deploy-preview-200--stanford-alumni-uat.netlify.app/travel-study/destinations/
2. Test all responsive …
> ADAPT-3811, ADAPT-3727: Filter page styles, Hero finetune

- static/_redirects
- Adds another redirect for Home
- Today if possible
- Medium
2. Navigate to /home
3. Verify that you land on the NEW homepage
- Other PRs
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack …
> ADAPT-3826: Update redirect for home

- src/components/page-types/TripPage/TripPage.jsx
- src/components/page-types/TripPage/TripPageExtensionSection.jsx
- src/components/page-types/TripPage/TripPageOverviewSection.jsx
- src/types/TripType.js
- Trip page changes and add option to hide certain sections manually on the page
1. Go to https://deploy-preview-229--stanford-alumni.netlify.app/travel-study/trips/botswana-south-africa-and-zambia
2. Check that the "Duration" in the Overview section only displays # of days (no # of nights)
3. Scroll to the Trip Extension section
4. Check that the right sidebar has these items
5. Go to http://app.storyblok.com/#!/me/spaces/118608/stories/0/0/70268404 and review locally
6. Check that you can hide the "Faculty", "Itinerary", "Trip Extension", "Trip Details" and the …
> ADAPT-3990: Trip Page changes and options to hide sections

- src/components/composite/TripFilterList/TripFilterList.jsx
- src/components/simple/FilterCheckbox/FilterCheckbox.jsx
- src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
- Add the count next to the filter facets
1. Go to https://deploy-preview-234--stanford-alumni.netlify.app/travel-study/destinations/
2. Check that the count is displayed next to the checkbox labels
3. Look at code
- Other PRs
- [AMP …
> ADAPT-3999: Add filter facet count to Trip Filter page

- src/utilities/filterTrips.js
- Switched out native `Date` parser for luxon in trip filtering hook. The combination of the Storyblok date fields (`2021-01-0-22 00:00`) combined with the limitations of iOS Safari native Date parser was causing invalid date object comparison.
- End of Sprint
1. Visit the destinations page in iOS Safari: https://deploy-preview-236--stanford-alumni.netlify.app/travel-study/destinations/
2. Verify that year, month and duration filters are displaying and working as expected
> ADAPT-4029 | @mattanglin | missing filter facets in mobile

- src/components/cards/basicCardContent.js
- src/components/page-types/TripPage/TripPageRelatedTripsSection.jsx
- src/components/page-types/TripPage/TripPageRelatedTripsSection.styles.js
- Change "Related Trips" section background to SAA Black.
- Support for Basic Cards (vertical and horizontal) without a headline
1. Go to https://deploy-preview-237--stanford-alumni.netlify.app/travel-study/trips/botswana-south-africa-and-zambia
2. Scroll to the bottom and see that the "Related Trips" section has black background.
3. Go to https://deploy-preview-237--stanford-alumni.netlify.app/test/yvonne/test-horizontal-basic-cards/
4. Check that in the first row, the card with the headline (left), and the card without the headline (right) both have the top of …
> ADAPT-4018, ADAPT-4028: Related trips background color change; Basic Cards tweak

- .github/workflows/merge-to-stage.yml
- netlify.toml
- plugins/netlify-plugin-contextual-auth/index.js
- plugins/netlify-plugin-contextual-auth/manifest.yml
This PR is infrastructure for having a "staging" or "preview" environment for the SAA Alumni Site. In this PR i've added a new workflow that will sync our `staging` branch with `dev` anytime anything is pushed to `dev`. I've setup a Netlify branch-deploy for our `staging` branch so once `dev` is synced with `staging` Netlify will kick off a `staging` deploy. The build config for `staging` includes a Storyblok preview api-key which will pull content in "Draft" status from our PROD Storyblok space. I've additionally added a custom Netlify plugin that will conditionally add auth headers based on deploy context/branch so that our deployed staging environment will have some basic protection.
- Added custom plugin for netlify contextual auth headers
- Added workflow to keep `staging` branch in …
> ADAPT-4026 | @mattanglin | staging site

- gatsby-node.js
- package-lock.json
- Cherry picks commit 412c340ef0bce9884baa3bb8d595552b5b4b413f out of dev for deployment
- Today would be nice
- Medium / High
> ADAPT-3983: Remove 403/404 paths as they are now redirects. (#233)

- gatsby-browser.js
- package-lock.json
- src/components/identity/global-header/GlobalHeader.jsx
- src/components/identity/masthead.js
- src/components/search/searchModal.js
- src/components/storyblok/globalHeader.jsx
- Created the search page for travel and study. The new page is on alumni dev storyblok
2. /travel-study/search to see the page 
3. or /travel-study and search in the header search which will take you to /travel-study/search not /search
- Other PRs
- [AMP …
> ADAPT-4031: Adding t/s search page

- src/components/page-types/TripPage/TripPage.jsx
- src/components/page-types/TripPage/TripPage.styles.js
- src/utilities/dates.js
- Hide all trip content except hero/ankle and display alert after trip has started
1. Go to https://deploy-preview-243--stanford-alumni.netlify.app/travel-study/trips/test-started-trip/
2. This trip has a start date set to June 2021, check that it's now displaying an alert at the top, and only the Hero + ankle are displayed like in the mockup
3. Go to a trip with start date in 2022 https://deploy-preview-243--stanford-alumni.netlify.app/travel-study/trips/trip-preset-cruise
4. Check that all the trip content renders and there is …
> ADAPT-4020, ADAPT-4021: Hide all trip content except hero and display alert after trip has started

- src/components/cards/iconCard.js
- src/utilities/richTextRenderer.js
- A couple of Trip Page a11y fixes (see things called out below). This should be the last of a11y fixes from the SODA team for T/S.
- Dec 10 if possible, so we can cut a release that includes this work before holiday
1. Go to https://deploy-preview-258--stanford-alumni.netlify.app/travel-study/trips/trip-preset-standard/
2. Scroll to Faculty Leader section below the video, check that the quote in the card is now a blockquote
3. Scroll to the ankle, inspect the card headline, check that it's now a span instead of a heading. Check that it looks the same as before.
- Does this PR impact any particular …
> ADAPT-4133: Trip Page a11y fixes

- gatsby-node.js
> ADAPT-000: GraphQL inference for field_hideFromFilter_boolean

- gatsby-node.js
>  Hotfix: GQL Inference for field_hideFromFilter_boolean

- src/components/page-types/TripPage/TripPage.jsx
- src/components/page-types/TripPage/TripPage.styles.js
- Add 0.4" print margin to paper (when printing PDF)
- I'm using the pageStyle option in the react-to-print package that we're using
https://github.com/gregnb/react-to-print
1. Go to https://deploy-preview-268--stanford-alumni.netlify.app/travel-study/trips/botswana-south-africa-and-zambia
2. Click on the "Print" button in the Overview section
3. Preview a PDF print 
and see that there is a 0.4" margin all around each page similar to this:
- Other PRs
- Any other contextual …
> ADAPT-4209: Add 0.4" print margin to Trip Page

- gatsby-node.js
- src/hooks/useTrips.js
- Filtered out the past trips to make sure none appear if the trip was not manually removed.
2. /travel-study/destinations/
3. Verify no past trips appear
- Other PRs …
> ADAPT-3993: Filter out the past trips

- static/_redirects
- Re: ADAPT-4224
- End of the week.
- 5/10
Review markup and ensure the build works. It will be hard to test unless you are savvy with editing your /etc/hosts
> ADAPT-4224: Redirect for trusteenominations

- static/_redirects
- SAA has moved Trustees, Volunteer leadership, and Beyond the Farm onto homesite. These redirects represent changes to existing redirects for the first two sites, and new redirecgs for BTF.
- No set date. Soon would be nice!
- 5
2. Go to a URL like <localhost>/get/page/volunteering/beyondthefarm/
3. Verify that it goes to <localhost>/volunteer/beyond-the-farm/
- ADAPT-4222
- Other PRs …
> ADAPT-4222: Updating redirects with new locations

- README.md
- example.env
- gatsby-config.js
- netlify.toml
- package-lock.json
- package.json
- plugins/netlify-plugin-vault-variables/README.md
- plugins/netlify-plugin-vault-variables/index.js
- plugins/netlify-plugin-vault-variables/manifest.yml
- plugins/netlify-plugin-vault-variables/package.json
- plugins/netlify-plugin-vault-variables/script.js
- Ports vault variable management strategy from give.stanford.edu
- Whenever
- Low
1. Review code
2. Review preview build website for irregularities
3. Check out branch and follow installation instructions to get a local site up and running
4. Review vault.stanford.edu and the giving secrets for any irregularities
5. Review readme instructions
6. Run installation steps and validate you get a running local environment
> ADAPT-4216: Port Vault variable management strategy.

- README.md
- Remove the mention of using `netlify env:set VAR_NAME value` because I actually don't really mean that
1. Look at the README.md changes
- Other PRs …
> Update README.md so it's clearer

- plugins/netlify-plugin-wildcard-404-redirect/index.js
- Use this to prevent the 304 redirects for now
- Still haven't been able to isolate this issue
> ADAPT-000: Redirect hardwire 

- src/components/partials/seo.js
- Adds "| Stanford Travel/Study" to the og:title (used when sharing to Facebook and other social platforms). 
- By end of sprint (Wed. Feb 16th)
- Moderately Low. Just helps reduce ambiguity on the titles used when posting to social media sites. 
1. Open Netlify preview, and visit any of the pages in the Travel Study section.
2. Inspect the source code using dev tools, and search for the "og:title" metatag. You should see " | Stanford Travel/Study" appended to the page title.
3. If you try sharing the URL on facebook or another social media site, you should see this title being used as well. (Note that sharing may not work for non-prod environments, due to password protection or other restrictions)
- …
> ADAPT-4381: Adjusted og:titles for Travel Study pages.

- netlify.toml
- Adds 'unsafe-eval' directive to content security policy, to allow for embedding of AdPlugg ads.
- Friday, Feb. 11th.
- 7/10? Issue does not affect anything currently on production, but is blocking rollout of a new feature.
1. Visit the following test page, where an embedded ad is present: (link removed)
2. Validate that the ad is displaying, and that the content-security-policy error is no longer in the console.
- Other PRs
- [Accessibility Manual …
> ADAPT-4307: Added unsafe-eval to Netlify security policy to allow AdPlugg embeds.

- src/components/partials/seo.js
> Hotfix: use existing isTravelStudy variable for pathname check for ogTitle

- lambda/auth.js
- netlify.toml
- src/components/auth/AuthIdleTimeoutOverlay.js
- src/components/auth/AuthenticatedPage.js
- src/components/navigation/accountLinks.js
- src/contexts/AuthContext.js
- static/_redirects
From our working session today.
> fixup! wip.

- lambda/auth.js
- package-lock.json
- package.json
- A breaking change needed to be made to adapt-auth-sdk when completing the work integrating it into My Account in ADAPT-4173. This PR refactors the auth callback to account for this change. 
- By March 1st. 
- High: If adapt-auth-sdk is updated to latest version without this PR, the authentication workflow will break. 
3. Verify...
- Other PRs …
> ADAPT-4173: Refactored callback to account for breaking change in adapt-auth-sdk.

- lambda/auth.js
- Fixes issue with incorrect login provider URL being used on Netlify environments.
- Issue was caused by limitation with https://github.com/bencao/netlify-plugin-inline-functions-env 
- It only replaces environment variable usages inside of the functions directory, so the values in the adapt-auth-sdk package in node_modules were ignored. 
- High
1. Open the Netlify preview site in a browser.
2. Open Chrome Dev Tools, select the network tab, and check the "preserve logs" checkbox.
3. Click the login button in the header.
4. Check the "doc" filter in the Network tab, and look for the redirect to the SP URL. Make sure it points to the "alumni-sso-uat.stanford.edu" subdomain.
- JIRA …
> ADAPT-4534: Fix bug with incorrect login provider URL.

- src/components/embed/giveGabForm.js
- src/utilities/giveGabVars.js
- Add and configure global variables for Additional Payment, Notify Me, and Custom Journey forms.
- end of sprint Mochi
2. Navigate to [`/test/rebecca/tsgg-additional-payment-form/`](https://deploy-preview-303--stanford-alumni.netlify.app/test/rebecca/tsgg-additional-payment-form/) Note: You'll be redirected to login. 
3. Confirm that the following fields are pre-filled
- Digital Name
- First Name
- Last Name
- Email
Data that is currently not available but should pre-fill as well:
- Address
- Address 2
- City
- State
- Zip
- Country
4. Navigate to [`/test/rebecca/tsgg-notify-me/`](https://deploy-preview-303--stanford-alumni.netlify.app/test/rebecca/tsgg-notify-me)
5. Confirm the the following fields are pre-filled
- Email
6. Navigate to …
> ADAPT-4412 | @rebeccahongsf | Add and configure global variables

- README.md
> nojira | @rebeccahongsf | remove tsgg dev from readme

- .github/release-drafter.yml
- .github/workflows/release.yml
- src/components/composite/accordion.js
- update tsgg with dev branch
1. Review code
> nojira | @rebeccahongsf | update tsgg with dev branch

- src/api/auth/profile.js
- src/components/navigation/accountLinks.js
- src/contexts/AuthContext.js
- src/utilities/MegaProfile.js
- add additional mp data endpoints
- add conditional for 404
- end of Nutella sprint
2. Log in as `zguan`
3. Navigate to [`api/auth/profile`](https://deploy-preview-310--stanford-alumni.netlify.app/api/auth/profile)
4. Confirm that the user's following information has been returned
- Addresses
- Contact
- Emails
- Phone Numbers
5. Review code and see if anything smells.
6. Determine if additional endpoint data is needed.
- ADAPT-4438
- ADAPT-4439
> ADAPT-4438 | @rebeccahongsf | add additional mp data endpoints

- src/components/navigation/accountLinks.js
- fix userProfile user first and last name
- asap
1. Navigate to...
2. Verify that you are able to login successfully 
- ADAPT-4438
> ADAPT-4438| @rebeccahongsf | fix userProfile first and last name

- gatsby-config.js
- src/components/components.js
- src/components/page-types/formPage/formPage.js
- src/components/page-types/formPage/tripCustomJourneys.js
- src/components/page-types/formPage/tripNotifyMe.js
- theme form page
- create [custom journeys component](https://www.figma.com/file/ZzuzKL805DOjPyT31ICc0c/Travel-Study-Microsite?node-id=3879%3A38751)
- end of Sprint O
2. Navigate to the following pages
- [Custom Journeys](https://deploy-preview-322--stanford-alumni.netlify.app/travel-study/custom-journeys-form/)
- [Additional Payment](https://deploy-preview-322--stanford-alumni.netlify.app/travel-study/additional-payment-form/)
- [Notify Me: Italy](https://deploy-preview-322--stanford-alumni.netlify.app/travel-study/italy-notify-me-form)
3. Compare to[ Form Wireframes mock](https://www.figma.com/file/ZzuzKL805DOjPyT31ICc0c/Travel-Study-Microsite?node-id=3879%3A38751)
4. See if any of the code smells or if there is a more efficient way to style
- ADAPT-4416
> ADAPT-4416 | @rebeccahongsf | theme form page-type component

- static/_redirects
- Redirects for Young Alumni
- Friday the 29th
@buttonwillowsix Please remove the redirect from Storyblok as we have to handle this special case.
> ADAPT-4909: Redirect young alumni

- src/components/page-types/formPage/formPage.js
- src/components/page-types/formPage/tripCustomJourneys.js
- src/components/page-types/formPage/tripNotifyMe.js
- implement ux form theme feedback
- End of spring Q
2. Navigate to the following pages and confirm their related changes:
3. [Notify Me: ](https://deploy-preview-333--stanford-alumni.netlify.app/travel-study/italy-notify-me-form/)
- Heading 1 has been changes to `Notify Me:`
- 72px margin bottom has been added under the main body of text (above the Dates)]
- Back to font is now weight 400
4. [Custom Journeys](https://deploy-preview-333--stanford-alumni.netlify.app/travel-study/custom-journeys-form)
- Back to font is now weight 400
5. Additional changes have been made in Storyblok to match the Figma design text
- ADAPT-4416
> ADAPT-4416 | @rebeccahongsf | implement ux form theme feedback

- src/components/embed/giveGabForm.js
- src/styles/forms.css
- Requested design fixes for the forms.
3. Verify...
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?us …
> ADAPT-4414: Form theming fixed

- gatsby-config.js
- src/components/embed/giveGabForm.js
- src/components/page-types/formPage/formPage.js
- src/components/page-types/formPage/tripCustomJourneys.js
- src/components/page-types/formPage/tripNotifyMe.js
- rework trip reference and remove duplicated information from gg component
- asap
1. Login as `zguan`
2. Confirm that the following pages still work as expected:
- [Notify Me: `/travel-study/italy-notify-me-form/`](https://deploy-preview-338--stanford-alumni.netlify.app/travel-study/italy-notify-me-form/)
- [Custom Journeys: `/travel-study/custom-journeys-form/`](https://deploy-preview-338--stanford-alumni.netlify.app/travel-study/custom-journeys-form/)
- ADAPT-4679
> ADAPT-4679 | @rebeccahongsf | rework trip reference and remove duplicated information from gg component

- src/utilities/giveGabVars.js
- fixup incorrect obj ref
- n/a
1. Confirm the first and last name is correctly populating in GG forms
> nojira | @rebeccahongsf | fixup incorrect obj ref

- src/components/page-types/TripPage/TripPage.jsx
- src/components/page-types/registrationFormPage/registrationFormPage.js
- add trip post extension options
- End of Sprint R
1. Review Trip StoryBlok post extension fields
2. Review `/travel-study/destination/italy-extension` and `/travel-study/italy-extension/registration`
- ADAPT-4681
> nojira | @rebeccahongsf | add trip post extension options

- src/components/page-types/formPage/formPage.js
- fix up one column layout theme
- End of Sprint R
1. Review one column layout at Additional Payment page:
https://deploy-preview-351--stanford-alumni.netlify.app/travel-study/additional-payment-form/
- ADAPT-4416
> ADAPT-4416 | @rebeccahongsf | fixup one column layout theme

- src/components/media/cardImage.js
- Fixes hydration bug causing incorrect images to display on Destination pages, when viewing paged results.
- As soon as possible (next 1-2 days).
- Moderately High. (Fixes defect currently on production. Defect does not break site critical functionality - but is disorientating)
1. Go to [Destinations](https://alumni.stanford.edu/travel-study/destinations) 
2. Use the pager to navigate to page 2 or 3. 
3. Reload the page.
4. Before fix, you would see the images from the first page of results rather than the correct images for the selected page.
5. After fix, the images should match with the cards as expected. 
Note that this issue cannot be reproduced using `gatsby develop`, so if testing locally, you'll need to use `gatsby build` and `gatsby serve`. 
- Does this PR impact any particular …
> ADAPT-4977: Fixed hydration defect affecting images on Travel Study destinations.

- static/gg-test/00-template.html
- static/gg-test/form-scenario/03-test.html
- static/gg-test/form-scenario/04-test.html
- static/gg-test/form-scenario/05-test.html
- static/gg-test/traveler-scenario/05-test.html
- static/gg-test/traveler-scenario/06-test.html
- static/gg-test/traveler-scenario/07-test.html
- static/gg-test/traveler-scenario/08-test.html
- static/gg-test/traveler-scenario/09-test.html
- static/gg-test/traveler-scenario/10-test.html
- static/gg-test/traveler-scenario/11-test.html
- static/gg-test/traveler-scenario/12-test.html
- static/gg-test/traveler-scenario/13-test.html
- resolve su_reg type difference in api data
- tbd
1. Review tests within  [GG Scenarios](https://docs.google.com/spreadsheets/d/1vhcBxwNQXkyrMqlpzVDKqEVx_2A8gU5WacLhIAq8Flg/edit#gid=576643898)
- ADAPT-4979
> ADAPT-4979 | @rebeccahongsf | resolve su_reg type difference in api data

- static/gg-test/00-template.html
- static/gg-test/form-scenario/03-test.html
- static/gg-test/form-scenario/04-test.html
- static/gg-test/form-scenario/05-test.html
- static/gg-test/traveler-scenario/08-test.html
- static/gg-test/traveler-scenario/09-test.html
- static/gg-test/traveler-scenario/10-test.html
- update test data su_reg `Related contact` cap
- tbd
1. Review tests within  [GG Scenarios](https://docs.google.com/spreadsheets/d/1vhcBxwNQXkyrMqlpzVDKqEVx_2A8gU5WacLhIAq8Flg/edit#gid=576643898)
- ADAPT-4979
> ADAPT-4979 | @rebeccahongsf | update test data su_reg related contact cap

- src/components/page-types/formPage/tripCustomJourneys.js
- src/components/page-types/formPage/tripNotifyMe.js
- fix back to link for notify me and custom journeys form
- asap
1. Review the `Back to` link on the following pages:
- `/travel-study/italy-notify-me-form`
- `travel-study/custom-journeys-form`
> nojira | @rebeccahongsf | fix back to link for notify me and custom journeys form

- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/tripTravelerCard.js
- src/components/page-types/registrationFormPage/tripTravelerList.js
- src/components/page-types/registrationFormPage/tripTravelerListItem.js
- src/contexts/FormContext.js
- restructure interstitial theme
- Sprint T
1. Navigate to [`travel-study/italy/registration`](https://deploy-preview-365--stanford-alumni.netlify.app/travel-study/italy/registration)
2. Compare to [figma mock designs](https://www.figma.com/file/ZzuzKL805DOjPyT31ICc0c/Travel-Study-Microsite?node-id=7645%3A114569)
3. Review code
- ADAPT-4678
> ADAPT-4678 | @rebeccahongsf | restructure interstitial theme

- src/utilities/giveGabVars.js
- quick fix for incorrect first name reference in user session data
- Sprint T
1. Login on preview site
2. Navigate to `travel-study/italy-notify-me-form`
3. Verify that the first and last name prefill correctly (no undefined)
> nojia | @rebeccahongsf | quick fix for incorrect first name reference in user session data

- src/components/page-types/formPage/formPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/components/page-types/registrationFormPage/tripTravelerCard.js
- add saa black dark to interstitial page and single col form theme
1. Review changes and confirm they match the figma mock
- `travel-study/italy/registration`
- `travel-study/italy/registration/form`
- `travel-study/additional-payment-form`
2. Review code
- ADAPT-4678
> ADAPT-4678 | @rebeccahongsf | add saa black dark to interstitial page and single col form theme

- static/gg-test/form-scenario/03-test.html
- static/gg-test/form-scenario/09-test.html
- static/gg-test/traveler-scenario/08-test.html
- static/gg-test/traveler-scenario/09-test.html
- givegab reg test form updates from GG Registration Form review meeting
- asap
1. Confirm that ACT items from [GG Registration Test spreadsheet](https://docs.google.com/spreadsheets/d/1vhcBxwNQXkyrMqlpzVDKqEVx_2A8gU5WacLhIAq8Flg/edit#gid=576643898) have been implemented.
- ADAPT-4979
> ADAPT-4979 | @rebeccahongsf | givegab reg test form updates

- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/tripTravelerListItem.js
- update prefix and user's prefill name
- single col styling adjustments (ADAPT-4678)
1. Login and confirm that in the event that the user has no prefix/title, `Mx.` is assigned as the prefix.
2. Review code
- ADAPT-4978
- ADAPT-4979
> ADAPT-4979 | @rebeccahongsf | update prefix and user's prefill name

- src/components/embed/giveGabForm.js
- static/scripts/travel-study/gg-form.css
- static/scripts/travel-study/gg-form.js
- static/scripts/travel-study/gg-trip-form.js
- update radio button to gradient
- update Back form button to gradient
- update Next form button to Digital Red
- add conditional render for pre and post markup ggform bloks
- update staff name gg variable
3. Verify...
- ADAPT-5020
- ADAPT-5088
> ADAPT-5020 | @rebeccahongsf | form adjustments

- static/scripts/travel-study/gg-form.css
- static/scripts/travel-study/gg-form.js
- static/scripts/travel-study/gg-trip-form.js
- add gradient to table
- adjust spacing
- adjust font-sizes
1. Review code
2. Review theme
- ADAPT-5020
> ADAPT-5020 | @rebeccahongsf | adjust internal form theme

- src/components/cards/protectedContentItem.js
- Add background color option to protected content item
- Soon
2. Go to the Storyblok DEV space
3. In Protected Content folder, play around with the existing Protected Content Items, or create a new one
4. Verify that you can change the background color of the content
- Other PRs
- [AMP …
> ADAPT-5098 | Add background color option to protected content item

- static/scripts/travel-study/assets/arrow-down.svg
- static/scripts/travel-study/assets/calendar.svg
- static/scripts/travel-study/gg-form.css
- static/scripts/travel-study/gg-trip-form.js
- add urlData param to trip form
- End of sprint Udon
3. Verify...
- ADAPT-5088
> ADAPT-5088 | @rebeccahongsf | add urlData to trip form

- src/components/cards/protectedContentItem.js
- updates from dev branch
3. Verify...
- ADAPT-5034
> ADAPT-5034 | @rebeccahongsf | dev updates

- static/scripts/travel-study/gg-form.css
- update trip information h3 font size
3. Verify...
- ADAPT-5020
> ADAPT-5020 | @rebeccahongsf | oneliner font size fix

- static/scripts/travel-study/gg-form.css
- back button font accessibility fix
3. Verify...
- ADAPT-5020
> ADAPT-5020 | @rebeccahongsf | back button font accessibility fix

- src/components/page-types/registrationFormPage/registrationFormPage.js
- account for direct navigation to regForm — [ref to Dave Nicely's basecamp message](https://3.basecamp.com/3590034/buckets/26004243/messages/5106169023)
- This should resolve any issues with when the user navigates directly to the registration page and registers from there.
- n/a
1. Navigate to `travel-study/italy-extension/registration/form`
2. Confirm that the `su_did` adc value has been filled through the browser console
3. Review code
> nojira | @rebeccahongsf | account for direct navigation to regForm

- src/api/auth/login.js
- src/components/auth/AuthenticatedPage.js
- src/components/navigation/accountLinks.js
- Ensure final_destination parameter is not undefined by using the useLocation hook.
- ASAP
- 900, TST is getting error reports 
1. Review the code
2. On your mobile phone navigate to the preview URL
3. Click on the login button on the home page and ensure you get to Stanford Pass
4. Go back
5. Navigate to an interior page
6. Click on the login button and ensure you get to Stanford pass
7. Complete login
8. Ensure you return back to the page you were on.
> ADAPT-5109: Mobile login issues for final_destination

- src/api/auth/login.js
- src/components/auth/AuthenticatedPage.js
- src/components/cards/protectedContentItem.js
- src/components/navigation/accountLinks.js
> Release V1.0.2

- src/utilities/isStoryblokEditor.js
- Fixes issue with auth passthrough for Storyblok Editor preview not working on Netlify environments.
- Issue turned out to be that Netlify automatically adds a trailing slash to paths. So the check for the "/editor" path was failing, as Netlify was redirecting to "/editor/".
1. Edit form page in Storyblok, such as https://app.storyblok.com/#!/me/spaces/145938/stories/0/0/114756809?env=Deploy%20Preview 
2. Select the deploy preview url (deploy-preview-394) in the dropdown.
3. Validate that it shows the form page rather than redirecting to the login page.
- Does this …
> ADAPT-4892: Fixed issue with editor authentication passthrough not working on Netlify.

- src/styles/forms.css
> ADAPT-5009: Thank you page theming

- src/components/composite/HeroImage/HeroImage.styles.js
- src/components/page-types/formPage/formPage.js
- src/components/page-types/formPage/tripCustomJourneys.js
- src/components/page-types/formPage/tripNotifyMe.js
- src/components/page-types/formPage/tripNotifyMe.styles.js
- src/tailwind/plugins/theme/colors.js
- Notify Me Round 1 QA feedback
- 07/12/2022
1. Review code
2. Navigate to [`/travel-study/italy-notify-me-form`](https://deploy-preview-392--stanford-alumni.netlify.app/travel-study/italy-notify-me-form/)
3. Compare to Figma mock 😄 
- ADAPT-5006
- ADAPT-5008
> ADAPT-5006 | @rebeccahongsf | notify me r1 qa

- src/components/composite/Alert/globalAlert.js
- We have been directing users to our internal SNOW form for feature requests. Requests need to go to TST!
-Soonish?
- Not so critical, since we can route the tickets. Just a bit annoying!
1. Try to login badly
2. Fail
3. Get the error message. Hopefully go to a form that is part of alumni/donor services
- Other PRs
- …
> Update globalAlert.js to go to TST form

- src/components/page-types/registrationFormPage/registrationFormPage.js
- in the event the user bookmarks the registration form, we want to redirect them to the interstitial page to select users
1. Login as test user
2. Navigate to [`/travel-study/destinations/italy-extension/register/form`](https://deploy-preview-399--stanford-alumni.netlify.app/travel-study/destinations/italy-extension/register/form)
3. Confirm that you are redirected to the interstitial page
4. Review code
- ADAPT-5112
> ADAPT-5112 | @rebeccahongsf | redirect from registration form

- src/utilities/mocks/fullgg.js
- Fixes authentication pass-through for Storyblok editor preview.
3. Verify...
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1O …
> ADAPT-4892: Fixed authentication pass-through

- src/components/page-types/registrationFormPage/registrationFormPage.js
- adjust redirect location and conditional
3. Verify...
- ADAPT-5112
> ADAPT-5112 | @rebeccahongsf | adjust redirect location and conditional

- src/components/composite/Alert/globalAlert.js
- Change in SNOW form in global alert error.
> Release V1.0.3

- static/scripts/travel-study/assets/arrow-down.svg
- static/scripts/travel-study/gg-form.css
- static/scripts/travel-study/gg-form.js
- static/scripts/travel-study/gg-trip-form.js
- staff form fixup from round 1 of QA
3. Verify...
- ADAPT-5139
> ADAPT-5139 | @rebeccahongsf | staff form fixup

- static/scripts/travel-study/gg-form.css
- static/scripts/travel-study/gg-trip-form.js
- staff form quick fix before round 2 of reviews with Bhavika
3. Verify...
- ADAPT-5139
> ADAPT-5139 | @rebeccahongsf | staff form quick fix

- static/scripts/travel-study/gg-form.css
> ADAPT-5139 | @rebeccahongsf | staff forms fixup r2

- src/api/auth/login.js
- src/components/composite/Alert/globalAlert.js
> nojira | @rebeccahongsf | dev updates

- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- patch regForm storyblok authoring exp
- ADAPT-5094
> ADAPT-5094 | @rebeccahongsf | patch regForm storyblok authoring exp

- src/components/identity/GlobalHeader/GlobalHeader.styles.js
- src/components/navigation/accountLinks.js
- src/styles/global.css
3. Verify...
- Other PRs
- [HTML …
> ADAPT-5091: Check if is authentificated before showing the user button

- src/components/page-types/formPage/formPage.js
- Add trip dates for Notify Me forms
1. Login as a test user
2. Navigate to [`/travel-study/ts-test/italy-notify-me-form/`](https://deploy-preview-416--stanford-alumni.netlify.app/travel-study/ts-test/italy-notify-me-form/)
3. Verify that the `su_trip_start_date` and `su_trip_end_date` are prefilling
- ADAPT-5212
> ADAPT-5212 | @rebeccahongsf | Add trip dates for Notify Me forms

- src/components/layout/ProtectedContentWrapper.jsx
-  adjust access denied text align and loading text
> nojira | @rebeccahongsf | adjust access denied text align and loading text

- static/scripts/travel-study/gg-trip-form.js
- add getDateOnly func for internal forms
3. Verify...
- ADAPT-5215
> ADAPT-5215 | @rebeccahongsf | add getDateOnly func for internal forms

- src/components/page-types/formPage/formPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/utilities/transformDate.js
- static/scripts/travel-study/gg-trip-form.js
> ADAPT-5214 | @rebeccahongsf | add format date functions

- src/components/identity/GlobalHeader/GlobalHeader.styles.js
- src/components/navigation/accountLinks.js
- src/styles/global.css
* ADAPT-5091: Check if is authentificated before showing the user button
* ADAPT-5091: Add placeholder for loading login link
> Release V1.0.4

- src/components/page-types/formPage/formPage.js
- src/components/page-types/formPage/formPage.styles.js
- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/interstitialPage.styles.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.styles.js
- src/styles/forms.css
- update form styles
- update Perks error 
To be reviewed with Bhavika this Friday, 08/5/2022 😸 
- [Additional payment](https://deploy-preview-421--stanford-alumni.netlify.app/travel-study/ts-test/additional-payment-form/)
- [Notify Me](https://deploy-preview-421--stanford-alumni.netlify.app/travel-study/ts-test/italy-notify-me-form)
- ADAPT-5141
> ADAPT-5141 | @rebeccahongsf | update form styles

- src/components/embed/giveGabForm.js
- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.styles.js
- src/styles/forms.css
- registration form fixes R1
- ADAPT-5141
> ADAPT-5141 | @rebeccahongsf | registration form fixes

- src/components/page-types/formPage/formPage.js
- src/components/page-types/formPage/formPage.styles.js
- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/styles/forms.css
> ADAPT-5141 | @rebeccahongsf | form fixes

- src/styles/forms.css
- static/scripts/travel-study/gg-form.css
- static/scripts/travel-study/gg-form.js
- static/scripts/travel-study/gg-trip-form.js
- Staff form fixes 
- Ext form fixes
- ADAPT-5139
> ADAPT-5139 | @rebeccahongsf | staff form fixes

- src/components/embed/giveGabForm.js
- src/components/page-types/formPage/formPage.js
- src/components/page-types/formPage/formPage.styles.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.styles.js
- src/styles/forms.css
- static/confirmation-msg/custom-journeys-form.html
- static/confirmation-msg/notify-form.html
- static/confirmation-msg/payment-form.html
- static/confirmation-msg/reg-form.html
- static/scripts/travel-study/gg-form.css
- update confirmation message styles
- ADAPT-5229
> ADAPT-5229 | @rebeccahongsf | update confirmation message styles

- src/styles/forms.css
- static/scripts/travel-study/gg-form.css
- static/scripts/travel-study/gg-trip-form.js
- update loading animation and form styles
- ADAPT-5139
> ADAPT-5139 | @rebeccahongsf | update loading animation and form styles

- src/components/layout/ProtectedContentWrapper.jsx
3. Verify...
- Other PRs
- [HTML …
> ADAPT-5216: Center the logged in non-member content

- src/api/travel-study/reg/trip-deposit.js
- static/scripts/travel-study/gg-trip-form.js
-  fix registration type
3. Verify...
- ADAPT-5232
> ADAPT-5232 | @rebeccahongsf | fix registration type

- src/components/page-types/registrationFormPage/registrationFormPage.js
- Fix offset registration header
- ADAPT-5141
> ADAPT-5141 | @rebeccahongsf | fix registration

- src/components/embed/dynaScript.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- static/scripts/travel-study/gg-form.js
- static/scripts/travel-study/gg-trip-form.js
- add anchor listener for successful
- update cancellation policy to open in new window/tab
1. Navigate to [`travel-study/destinations/italy-extension/register`](https://deploy-preview-437--stanford-alumni.netlify.app/travel-study/destinations/italy-extension/register)
2. Fill out form and on the payment page, confirm that the Cancellation Policy link opens in a new window/tab
4. Verify that upon successful submission, the browser scrolls back up to the top of the form.
5.  Review code
- ADAPT-5271
> ADAPT-5271 | @rebeccahongsf | add anchor listener for successful submission

- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- update primary registrant and unique id
1. Login as a test user
2. Navigate to [`travel-study/destinations/italy-extension/register`](https://deploy-preview-442--stanford-alumni.netlify.app/travel-study/destinations/italy-extension/register)
3. Select all travelers (excluding the registering user) 
4. Fill out the registration form
5. Review submissions in the Givegab UI
- ADAPT-5300
> ADAPT-5300 | @rebeccahongsf | update primary registrant and unique id

- src/components/navigation/MainNav/mainNavItem.jsx
https://stanfordits.atlassian.net/browse/ADAPT-3917
> ADAPT-3917: Add mobule only menu items

- src/components/page-types/registrationFormPage/tripTravelerCard.js
- src/contexts/FormContext.js
- rework remove button toggle
- we can retro-review during our 1:1?
2. Navigate to `travel-study/destinations/italy-extension/register`
3. Confirm that the Remove and Add buttons are still working as expected
- ADAPT-4686
> ADAPT-4686 | @rebeccahongsf | rework remove button toggle

- src/components/page-types/registrationFormPage/registrationFormPage.js
- conditionally display room category questions
1. Navigate to [`travel-study/destinations/italy/register`](https://deploy-preview-445--stanford-alumni.netlify.app/travel-study/destinations/italy/register)
2. Verify that the room category questions do not display
- ADAPT-5303
> ADAPT-5303 | @rebeccahongsf | conditionally display room category questions

- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/components/page-types/registrationFormPage/tripPrimaryCard.js
- src/components/page-types/registrationFormPage/tripTravelerList.js
- src/components/page-types/registrationFormPage/tripTravelerListItem.js
- src/contexts/FormContext.js
- enforce primary registrant to always attend trip
1. Login as a test user
2. Navigate to [`/travel-study/destinations/italy-extension/register`](https://deploy-preview-446--stanford-alumni.netlify.app/travel-study/destinations/italy-extension/register)
3. Verify that the primary registrant (logged in user) is preselected from the list.
4. Select additional travelers and continue to the form
5. Fill out form
6. Review GiveGab data
7. Review code
- ADAPT-5257
> ADAPT-5257 | @rebeccahongsf | enforce primary registrant to always attend trip

- src/utilities/transformDate.js
- update dob func
3. Verify...
- ADAPT-5341
> ADAPT-5341 | @rebeccahongsf | update dob func

- src/components/page-types/TripPage/TripPage.jsx
- src/components/page-types/TripPage/TripPageExtensionSection.jsx
- src/components/page-types/TripPage/TripPageOverviewSection.jsx
- src/components/page-types/formPage/formPage.styles.js
- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/interstitialPage.styles.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/components/page-types/registrationFormPage/tripPrimaryCard.js
- src/components/page-types/registrationFormPage/tripTravelerCard.js
- src/components/page-types/registrationFormPage/tripTravelerListItem.js
- src/styles/forms.css
- remove body field from sb
- update interstitial page to include deposit text
- update Mobile payment form styling
- fix additional payment column span 
1. Login as a test user
2. Navigate to `travel-study/destinations/italy/register`
3. Verify trip deposit copy appears (and the extension related copy does not)
4. Navigate to `travel-study/destinations/italy-extensions/register`
5. Verify trip and extension deposit copy appears
6. Confirm that the heading matches the [figma mock](https://www.figma.com/file/ZzuzKL805DOjPyT31ICc0c/Travel-Study-Microsite?node-id=7649%3A116924)
7. Move onto the registration form.
8. Confirm that the heading matches the [figma mock](https://www.figma.com/file/ZzuzKL805DOjPyT31ICc0c/Travel-Study-Microsite?node-id=8026%3A118750)
9. Fill out form and on the …
> ADAPT-5330 | @rebeccahongsf | update interstitial and form styling

- src/components/page-types/formPage/tripCustomJourneys.styles.js
- src/components/page-types/formPage/tripNotifyMe.styles.js
- update back to link style
2. Navigate to `travel-study/ts-test/italy-notify-me-form`
3. Verify that the Back to link appears in white text, digital red light icon. On hocus, there should be an digital red light underline
4. Navigate to `travel-study/ts-test/custom-journeys-form`
5. Verify that the Back to link appears in white text, digital red light icon. On hocus, there should be an digital red light underline
- ADAPT-5141
> ADAPT-5141 | @rebeccahongsf | update back to link style

- src/components/page-types/TripPage/TripPageOverviewSection.jsx
- src/components/page-types/registrationFormPage/interstitialPage.js
- update interstitial page copy
3. Verify...
- ADAPT-5355
> ADAPT-5355 | @rebeccahongsf | update interstitial page copy

- src/api/auth/profile.js
- src/contexts/AuthContext.js
- Handle the missing encodedsuid issue more gracefully.
- Allows user to log in and does not present yellow fail banner when MPAPI call fails.
> ADAPT-5247: Handle login error more gracefully.

- package.json
- src/api/auth/profile.js
- src/contexts/AuthContext.js
- ADAPT-5247: Handle login error more gracefully
> Release v2.0.1

- README.md
- Update README to match the script in `package.json`
3. Verify...
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs …
> Update README to match script name

- src/components/cards/TripCard/TripCard.jsx
- Fixes issues with links on second page pointing to wrong URL, when visited directly.
- This turned out to be the same hydration issue as with the images on #353 
- See: https://github.com/gatsbyjs/gatsby/discussions/17914 
3. Verify...
- Other PRs
- Anyone who should be notified? (`@mention` them …
> ADAPT-5412: Fixed hydration-caused issue with link mismatch on Destinations view.

- src/components/page-types/registrationFormPage/registationFormOptions.js
- src/utilities/giveGabVars.js
- type fix
- Other should be lowercase due to match GiveGab options
- asap
1. Checkout branch locally
2. Enable mockserver by adding `MEGAPROFILE_MOCK=true` in the `.env`
3. Navigate to `/travel-study/destinations/italy-test/register/form`
4. Continue onward to the registration form.
5. Verify that the prefilled email and phone number matches the preferred typed listed in their MP data at `/api/auth/profile`
6. Continue to the payment portion of the form and confirm no error appears.
7. Feel free to change the pref email and phone number types under `src/utilities/mocks/fullgg.js` to confirm that the proper email and phone numbers are being prefilled.
8. Review code 😎 
- ADAPT-5425
> ADAPT-5625 | @rebeccahongsf | type fix

- src/utilities/giveGabVars.js
- resolve email type issue for when pref email type is set to null
- asap 😸 
1. Checkout branch locally
2. Enable mockserver by adding `MEGAPROFILE_MOCK=true` in the `.env`
3. Navigate to `/travel-study/destinations/italy-test/register/form`
4. Continue onward to the registration form.
5. Verify that the prefilled email and phone number matches the preferred typed listed in their MP data at `/api/auth/profile`
6. Continue to the payment portion of the form and confirm no error appears.
7. Feel free to change the pref email and phone number types under `src/utilities/mocks/fullgg.js` to confirm that the proper email and phone numbers are being prefilled.
8. Review code 👁️ 
- ADAPT-5425
> ADAPT-5425 | @rebeccahongsf | resolve email type issue

- src/styles/forms.css
- update email type styling
- sooner would be awesome for UAT
1. Navigate to `/travel-study/destinations/italy-extension-text/register/`
2. Continue to form and fill out primary reg options
3. Add new traveler
4. Scroll down to Email Type section and confirm that "Other" is capitalized.
5. Review code
- ADAPT-5440
> ADAPT-5440 | @rebeccahongsf | update email type styling

- src/components/embed/dynaScript.js
- add scroll to top for discard registrant scenario
- eod 10/12 as T/S UAT would like to test
1. Log in as test user `zguan`
2. Navigate to [`travel-study/destinations/italy-test/register`](https://deploy-preview-482--stanford-alumni.netlify.app/travel-study/destinations/italy-test/register)
3. Select a minimum of one additional traveler
4. Move through the form until you get to the payment page
5. In the payment tally table, edit one of the additional travelers
6. Scroll to the bottom of the traveler's information form page and click `Remove Traveler`. You should then be brought back to the top of the form and see the payment tally table.
7. Review code 👾 
- ADAPT-5438
> ADAPT-5438 | @rebeccahongsf | add scroll to top for discard registrant scenario

- gatsby-node.js
- src/styles/forms.css
This release includes:
- scroll back to top when a traveler is removed
- hide remove button for primary registrant
- EOD, 10/14
1. Do the GH actions action?
> Release: v2.0.7

- src/styles/forms.css
- resolve specific use case remove traveler bug 
- Monday EOD, 10/17
1. Navigate to [`travel-study/destinations/italy-test/register`](https://deploy-preview-490--stanford-alumni.netlify.app/travel-study/destinations/italy-test/register)
2. Continue to the form with no additional travelers.
3. Continue to payment summary
4. Add new traveler
5. Edit you, the primary registrant
6. Scroll down and confirm the `X Remove Traveler` does not appear
7. Continue to the payment summary
8. Edit the newly added traveler
9. Scroll down and confirm the `X Remove Traveler` does appears
10. Review code 👾
> NOJIRA | @rebeccahongsf | resolve specific use case bug

- src/components/composite/HeroImage/HeroImage.jsx
- src/components/composite/HeroImage/HeroImage.styles.js
- src/components/embed/giveGabForm.js
- src/styles/forms.css
- Resolve missing hero gradient on Notify Me page
- Remove spaces from TripId to account for content authoring error
- Adjust mobile payment styling
- asap
2. Navigate to [Notify Me page](https://deploy-preview-494--stanford-alumni.netlify.app/travel-study/destinations/italy-test/notify/) and confirm the gradient is appearing
(Compared to PROD example: [Notify Me form](https://alumni.stanford.edu/travel-study/destinations/japan-2023/notify))
3. Review code
- ADAPTTS-233
- ADAPTTS-232
> NOJIRA | @rebeccahongsf | resolve missing hero gradient

- src/components/composite/HeroImage/HeroImage.jsx
- src/components/composite/HeroImage/HeroImage.styles.js
- src/components/embed/giveGabForm.js
- src/styles/forms.css
- Release recent fixes made per T/S request
- EOD
> Release: v2.0.9

- src/components/search/searchResults.js
- Fixing the optional chaining operator location addressed in https://github.com/SU-SWS/saa_alumni/pull/479
- Error can be seen by navigating to https://alumni.stanford.edu/search/?q=scotland
- ![Screen Shot 2022-10-17 at 4 11 03 PM](https://user-images.githubusercontent.com/49299083/196300469-e1b348e2-1c36-408a-b955-c8d673802ba7.png)
- After my fix (see https://deploy-preview-497--stanford-alumni.netlify.app/search?q=scotland), the page loads, but the result is still included, showing only the domain and link to the url
- ![Screen Shot 2022-10-17 at 3 57 01 PM](https://user-images.githubusercontent.com/49299083/196300844-282b0721-9956-4793-8c9c-ca2843f9d70a.png)
- asap
- How critical is this PR on a 1-10 scale? Also see [Severity …
> EXRESUPP-45 | @jdwjdwjdw | Search for term with missing content value causes WSOD

- static/scripts/travel-study/gg-form.css
- static/scripts/travel-study/gg-form.js
- static/scripts/travel-study/gg-trip-form.js
- Resolve persisting loader that should disappear once form loads
- Clean up Other radio button and field style
- Hide payment total for Hold Reg
- Add window.extension GG adc value
3. Verify...
- ADAPTTS-239
- ADAPTTS-241
- ADAPTTS-245
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)
> ADAPTTS-239 | @rebeccahongsf | resolve persisting loader

- package-lock.json
- package.json
- src/utilities/richTextRenderer.js
- Provides guard code for missing props
- Story page in question: https://app.storyblok.com/#/me/spaces/103430/stories/0/0/222994046/blok/84770d47-ee53-42ae-bd1f-736c32fced97
- Something has slipped into the wysiwyg and/or configuration for the wysiwyg that is causing a missing class prop to be passed into the resolver. I haven't dug into why or where but this PR patches the issue.
- EOD would be awesome
- High
1. Go to https://app.storyblok.com/#/me/spaces/103430/stories/0/0/222994046/blok/84770d47-ee53-42ae-bd1f-736c32fced97 and open your browser console. See an error for undefined value in `props.class` in the styledMarkResolver (https://github.com/claus/storyblok-rich-text-react-renderer/blob/master/src/index.js#L133)
2. Check out this branch and fire up your local and start the local …
> NoJira: WYSIWYG style guard code.

- gatsby-node.js
- configure gatsby node for membership pages creation
- asap (let's retroreview this, I anticipate possible iterations and cleanup)
3. Verify...
- ADAPTSM-35
> ADAPTSM-35 | @rebeccahongsf | configure gatsby node for membership pages creation

- src/components/components.js
- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/components/page-types/membershipFormPage/membershipFormPage.styles.js
- create membership form page
**Note:** will continue iterating on styles in ADAPTSM-35 and additional form related configuration will be done in ADAPTSM-27
- asap
1. Navigate to [membership registration page](https://deploy-preview-525--stanford-alumni.netlify.app/membership/register/)
2. Confirm that you are able to login and view the T/S form (a continue btn should display).
3. Review code
- ADAPTSM-26
- ADAPTSM-35
> ADAPTSM-26 | @rebeccahongsf | create membership form page

- src/components/page-types/membershipFormPage/membershipFormPage.js
-  fixup storyblok preview err
- rolling in this fix
1. Navigate to SB space and confirm that the [preview now displays properly](https://app.storyblok.com/#/me/spaces/184821/stories/0/0/224400868?env=Temp%3A%20PR%23529)
- ADAPTSM-25
> ADAPTSM-25 | @rebeccahongsf | fixup storyblok preview err

- src/components/page-types/membershipFormPage/membershipFormPage.styles.js
- remove sticky styling
- asap
1. Navigate to [`/membership/register/form`](https://deploy-preview-531--stanford-alumni.netlify.app/membership/register/form)
2. Confirm that the Welcome text moves with the page upon scroll (versus sticking to the top)
- ADAPTSM-35
> ADAPTSM-35 | @rebeccahongsf | remove sticky styling

- src/components/page-types/registrationFormPage/interstitialPage.js
- src/utilities/transformDate.js
- If no data is available from MP, set the birthday to undefined
3. Verify...
- ADAPTTS-249
> ADAPTTS-249: Dummy date

- src/utilities/transformDate.js
- fixup dob offset
- asap
1. Navigate to `travel-study/destinations/italy-test/register`
3. Proceed to the form
4. Inspect and confirm that `zguan`'s DOB `1988-01-01` is being passed in correctly
**Note:** DOB can be found at `api/auth/profile`
> nojira | @rebeccahongsf | fixup dob DATE offset

- src/components/page-types/membershipFormPage/MembershipCard.styles.js
- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.styles.js
- [ADAPTSM-45](https://stanfordits.atlassian.net/browse/ADAPTSM-45): DEV | Build out interstitial page — user card component
- Styling mostly complete, but will finish in future PR for - [ADAPTSM-46](https://stanfordits.atlassian.net/browse/ADAPTSM-46): THEME | Style interstitial page — user card component
1. Review code and preview at https://deploy-preview-535--stanford-alumni.netlify.app/membership/register and confirm all looks good.
- Other PRs
- Any other contextual …
> ADAPTSM-46 | @jdwjdwjdw | Build membership card component

- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.styles.js
- [ADAPTSM-43](https://stanfordits.atlassian.net/browse/ADAPTSM-43): THEME | Style interstitial page — type of registrant page
3. Verify...
- Other PRs …
> ADAPTSM-43 | @jdwjdwjdw | Update type of registrant page and styles

- src/components/page-types/membershipFormPage/MembershipCard.styles.js
- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/components/page-types/registrationFormPage/interstitialPage.js
- src/components/page-types/registrationFormPage/tripPrimaryCard.js
- src/components/page-types/registrationFormPage/tripTravelerCard.js
- src/components/page-types/registrationFormPage/tripTravelerList.js
- src/components/page-types/registrationFormPage/tripTravelerListItem.js
- src/contexts/FormContext.js
- Configure add/remove registrant functionality for membership card
- Rename formContext variables/actions to be more general (versus T/S specific)
**Note: Additional refinement for the data handling will come in [ADAPTSM-53](https://stanfordits.atlassian.net/browse/ADAPTSM-53) and [ADAPTSM-58](https://stanfordits.atlassian.net/browse/ADAPTSM-58)**
- no rush, I plan to review this with @jdwjdwjdw when we return from break
1. Navigate to [`/membership/register/related-contacts/`](https://deploy-preview-537--stanford-alumni.netlify.app/membership/register/related-contacts)
3. Select the related contact
4. Try to select the New Contact. You should not be able to select the user (additional styling to come).
5. Unselect the related contact and select New Contact.
6. Click …
> ADAPTSM-110 | @rebeccahongsf | Configure add/remove registrant functionality for membership card

- static/_redirects
- Adds associates redirect as we cant do this in the vanityurl.stanford.edu tool due to the 4 part domain.
> ADAPTSSS-707: Add associate redirect

- static/_redirects
- ADAPTSSS-707: Add associate redirect
> Release v3.0.3

- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- Fixup non-iterable err and scaffold primaryUser data
**NOTE:** Update MemberCard prop name from member to memberData for additional clarity
- asap
1. Navigate to [`/membership/register`](https://deploy-preview-551--stanford-alumni.netlify.app/membership/register)
2. Confirm that the page loads
3. Review code
- ADAPTSM-53
> ADAPTSM-52 | @rebeccahongsf | Fixup err and scaffold primaryUser data

- gatsby-node.js
- package-lock.json
- src/components/components.js
- src/components/page-types/membershipFormPage/membershipInstallmentsForm.js
- src/templates/storyblok-entry.js
- configure membership installments form generation
- create payment options data section in SB
- asap
1. Navigate to [SB membership form page](https://app.storyblok.com/#/me/spaces/184821/stories/0/0/224400868) and review the installments form section located in main content tab and the payment options data tab
**NOTE:** Payment options data display will be completed in [ADAPTSM-118](https://stanfordits.atlassian.net/browse/ADAPTSM-118)
2. Navigate to [`/membership/register/installments/form`](https://deploy-preview-547--stanford-alumni.netlify.app/membership/register/installments/form)
3. Confirm the the correct form is generated
4. Review code
- [ADAPT-117](https://stanfordits.atlassian.net/browse/ADAPTSM-117)
- [ADAPT-121](https://stanfordits.atlassian.net/browse/ADAPTSM-121) …
> ADAPT-121 | @rebeccahongsf | configure membership installments form generation

- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- update related contact prefill adc values
1. Navigate to `/membership/register/related-contacts/`
2. Select a related contact and click Next to navigate to the form page
3. Verify that the first and last name prefills in the recipient information section and Gift section is displayed.
4. Navigate back to `/membership/register/related-contacts/`
5. Select a new contact
6. Verify that the recipient information section and Gift section is displayed.
7. Review code 👾 
- ADAPTSM-58
> ADAPTSM-58 | @rebeccahongsf | update related contact prefill adc values

- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.styles.js
- [ADAPTSM-53](https://stanfordits.atlassian.net/browse/ADAPTSM-53): DEV | Configure the registrant prefill data values for the GiveGab form
2. Navigate to https://deploy-preview-552--stanford-alumni.netlify.app/membership/register and sign in as zguan
3. Verify that the select functionality, button disabling, and URL routing when you select the membership type looks correct.
4. Verify that the ADV values are correct.
5. Review code 🤖 
[ADAPTSM-53]: https://stanfordits.atlassian.net/browse/ADAPTSM-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ADAPTSM-53 | @jdwjdwjdw | Configure the registrant prefill data values for the GiveGab form

- static/scripts/travel-study/gg-form.css
- update confirmation message tally table styles for internal reg form
- asap
1. Check out this branch on your local and run `npm run dev`
2. Navigate to [ADAPT Demo registration page that sources styles and js locally](https://adaptdemo.sites.stanford.edu/test-staff-form-local-registration)
3. Login to access the form
4. Fill out and submit registration form with fake data
5. Review the confirmation message. It should look similar to this:
6. Review code
> nojira | @rebeccahongsf | update confirmation message tally table styles for internal reg form

- static/_redirects
- https://careers.alumni.stanford.edu -> https://alumni.stanford.edu/career-connections
- Sometime this week would be nice
- 5/10
1. Review code
2. I'll put in the DNS changes later.
> ADAPT-5509: Redirect careers.alumni.stanford.edu

- src/components/page-types/membershipFormPage/MembershipCard.styles.js
- src/components/page-types/membershipFormPage/membershipCard.js
- [ADAPTSM-46](https://stanfordits.atlassian.net/browse/ADAPTSM-46): THEME | Style interstitial page — user card component
1. Check out this branch or view the [preview site](https://deploy-preview-560--stanford-alumni.netlify.app)
2. login as zguan
3. Navigate to `/membership/register` https://deploy-preview-560--stanford-alumni.netlify.app/membership/register
4. Verify that membership card styles look correct in default state, selected, and newContact
[ADAPTSM-46]: https://stanfordits.atlassian.net/browse/ADAPTSM-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ADAPTSM-46 | @jdwjdwjdw | Style interstitial page — membership user card component

- static/scripts/travel-study/gg-trip-form.js
- update internal trip pre-extension data
- asap
1. Check out branch and spin up your local `npm run dev`
2. Navigate to [`ADAPT demo reg form`](https://adaptdemo.sites.stanford.edu/test-staff-form-local-registration) to source from your local
3. Search and select `Adriatic Sea 2023` or `400062`
4. Continue to the form
5. Verify that the pre/post extension questions appear toward the bottom of the form
6. Review code 👾
> nojira | @rebeccahongsf | update internal trip pre-extension data

- package-lock.json
- src/components/partials/seo.js
- src/utilities/createStories.js
- static/scripts/travel-study/gg-trip-form.js
- A content reference from somewhere was sneaking in as a story object
- Not sure where it came from
- Added extra try/catch on postscribe 
- End of the week
- 5/10
1. Review code
2. Pull down to local and set your STORYBLOK_ACCESS_TOKEN to point to the production environment
3. Spin up a local build
4. Navigate to the production storyblok space and edit the home page
5. Ensure you can change a field or value without it WSODing
6. Review preview build to ensure home page still loads with ads
> ADAPT-5539: Protect against content references in create blocks.

- src/components/page-types/registrationFormPage/interstitialPage.js
- src/styles/forms.css
- src/utilities/transformDate.js
- update date format to UTC
- fixup stripe saved payment button styling
- asap
1. Login as `zguan` 
2. Navigate to [`travel-study/destinations/italy-test/register`](https://deploy-preview-569--stanford-alumni.netlify.app/travel-study/destinations/italy-test/register)
3. Verify that the DOB matched the user (01/01/1988) by inspecting the browser console and entering in `window.prefillData`.
4. Review code 👾
> nojira | @rebeccahongsf | update date format to UTC

- static/_redirects
- https://careers.alumni.stanford.edu/resources --> https://alumni.stanford.edu/career-connections/resources
- https://careers.alumni.stanford.edu/students --> https://alumni.stanford.edu/career-connections/students
- https://careers.alumni.stanford.edu/offer-support --> https://alumni.stanford.edu/career-connections/offer-help
- https://careers.alumni.stanford.edu/faq --> https://alumni.stanford.edu/career-connections/faq
- https://careers.alumni.stanford.edu/* --> https://alumni.stanford.edu/:splat
- 5
1. Review code
2. Make sure the requested redirects in [ADAPT-5509](https://stanfordits.atlassian.net/browse/ADAPT-5509) works as expected
[ADAPT-5509]: https://stanfordits.atlassian.net/browse/ADAPT-5509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> ADAPT-5509: careers.alumni.stanford.edu redirects

- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- specify form options
2. Navigate to [`/membership/register`](https://deploy-preview-576--stanford-alumni.netlify.app/membership/register)
3. Select "Myself" and "One Time payment" then proceed to the form
4. Verify that only four options appear
5. Navigate back to [`/membership/register`](https://deploy-preview-576--stanford-alumni.netlify.app/membership/register)
6. Select "Myself" and "Installments" then proceed to the form
7. Verify that only three options appear
8. Navigate back to [`/membership/register`](https://deploy-preview-576--stanford-alumni.netlify.app/membership/register)
9. Select "Someone else" and from related contact(s) select `Xiaojing` then proceed to the form
10. Verify that only four option appear
11. Navigate back to …
> ADAPTSM-39 | @rebeccahongsf | specify form options

- src/components/page-types/membershipFormPage/MembershipCard.styles.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/components/page-types/membershipFormPage/relatedContactSelection.styles.js
- src/utilities/mocks/fullgg.js
- style related contacts for responsive
2. Enable mocksever: `MEGAPROFILE_MOCK = 'true'`
3. Navigate to `/membership/register/related-contacts` from [`/membership/register`](https://deploy-preview-577--stanford-alumni.netlify.app/membership/register)
4. Use inspect browser tool to verify the different breakpoints (xxl, xl, lg, md, sm, xs) with the [Figma mock (under components)](https://www.figma.com/file/BfEeWa39C6xT6muvdkBXsw/Membership-2022%2F23?node-id=1200%3A151628&t=kiPibX5XGabdV3Rj-1)
5. Review code 👾 
- ADAPTSM-56
- ADAPTSM-57
> ADAPTSM-56 | @rebeccahongsf | style related contacts for responsive

- static/_redirects
- Redirect for Students
- Normal
1. Review the code :D
> ADAPT-5548: Add redirects for Students.

- .github/release-drafter.yml
- .github/workflows/release.yml
> Try'n to fix the release things.

- src/components/page-types/membershipFormPage/MembershipCard.styles.js
- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.styles.js
- src/components/page-types/membershipFormPage/membershipPaymentOptions.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.styles.js
- [ADAPTSM-119](https://stanfordits.atlassian.net/browse/ADAPTSM-119): THEME | Style Installments Payment options
- I also made a few related fixups that I found in the membership card and type of registrant page
1. Check out this branch or view preview at https://deploy-preview-580--stanford-alumni.netlify.app
2. Navigate to [/membership/register](https://deploy-preview-580--stanford-alumni.netlify.app/membership/register) and login as `zguan`
3. Select `Myself` to display Payment Options
4. Review styles
5. Review code 🦕 
[ADAPTSM-119]: https://stanfordits.atlassian.net/browse/ADAPTSM-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ADAPTSM-119 | @jdwjdwjdw | style installments payment options

- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/membershipFormPage.styles.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- src/styles/forms.css
- style tally table and payment form fields
1. Navigate to [`/membership/register`](https://deploy-preview-590--stanford-alumni.netlify.app/membership/register)
2. Select `Myself`> `One-time Payment` and continue to form
3. Review the Membership select options and compare to figma
4. Review the membership select list and confirm that this matches figma
5. Then fill out the first form page and continue to the second page (payment fields)
6. Review payment fields and confirm the `Name on Card` section matches what is outlined in figma
7. Review responsiveness
8. Navigate back to [`/membership/register`](https://deploy-preview-590--stanford-alumni.netlify.app/membership/register)
9. Select `Myself`> `Installments` and continue to form
10. …
> ADAPTSM-31 | @rebeccahongsf | style tally table and payment form fields

- src/components/page-types/membershipFormPage/MembershipCard.styles.js
- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/membershipInfoText.js
- src/components/page-types/membershipFormPage/membershipInfoText.styles.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.styles.js
- [ADAPTSM-44](https://stanfordits.atlassian.net/browse/ADAPTSM-44): THEME | Style interstitial page — type of registrant page - Mobile
- [ADAPTSM-47](https://stanfordits.atlassian.net/browse/ADAPTSM-47): THEME | Style interstitial page — user card component - Mobile
- Responsive/style updates for the Membership Payment card. 
1. Check out this branch and navigate to `/membership/register` or view [preview](https://deploy-preview-591--stanford-alumni.netlify.app/membership/register). Sign in as `zguan`.
2. Review the page at `/membership/register` and confirm that all elements look correct across breakpoints and browsers
3. Review code 🐠 
[ADAPTSM-44]: https://stanfordits.atlassian.net/browse/ADAPTSM-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> ADAPTSM-47 | @jdwjdwjdw | Responsive styles and fixups for interstitial pages

- src/api/statuscake.ts
- Add endpoint that returns 200 ok for monitoring
Go to the preview build and visit https://deploy-preview-593--stanford-alumni.netlify.app/api/statuscake ensure you get a `200` with a body of `Ok`
> NoJira: Add statuscake api function for monitoring.

- src/api/statuscake.ts
- Adds function endpoint for monitoring
> Release v3.0.3 (#546)

- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- src/components/page-types/membershipFormPage/typeOfRegistrant.styles.js
- add transition to payment options
- asap
1. Navigate to [`/membership/register`](https://deploy-preview-592--stanford-alumni.netlify.app/membership/register)
3. Select `Myself` and verify that the Payment Options now transition to open vs. popping up.
4. Review code 🪴 
- ADAPTSM-147
> ADAPTSM-147 | @rebeccahongsf | add transition to payment options

- src/components/page-types/membershipFormPage/typeOfRegistrant.js
- src/utilities/mocks/affiliations.js
- add membership form flow for friend/non-alumni
- asap
1. Check out this branch and spin up your local with mockserver enabled (`MEGAPROFILE_MOCK = 'true'`)
2. Navigate to `/membership/register`
3. Select `Myself`. The payment options should not display
5. Continue to the form
6. Confirm that the form displays the following two options:
7. Now we'll test for `zguan` through the preview (or disable your mockserver)
8. Login as `zguan`
9. Navigate to `/membership/register`
10. Select `Myself`. The payment options should display
11. Select `Installment`
12. Continue to form
13. Confirm that the installments form displays:
14. Navigate to back to `/membership/register`
15. Select `Myself`. The payment options should display
16. Select `Full payment`
17.  Continue to form
18. Confirm that the …
> ADAPTSM-150 | @rebeccahongsf | add membership form flow for friend/non-alumni

- src/api/travel-study/trips/index.js
- Fixup missing trips
- asap for T/S QA
2. Navigate to https://dev--stanford-alumni.netlify.app/api/travel-study/trips
3. Verify that `poland-2024` does not exist
4. Navigate to https://deploy-preview-600--stanford-alumni.netlify.app/api/travel-study/trips
5. Verify that `poland-2024` exists
6. Review code 🌵
> NOJIRA | @rebeccahongsf | Fixup missing trips

- src/components/page-types/membershipFormPage/MembershipCard.styles.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.styles.js
- src/styles/forms.css
- [ADAPTSM-163](https://stanfordits.atlassian.net/browse/ADAPTSM-163): DEV | Add focus state to Membership Card
- I also added similar focus styles for the Membership Payment Card
1. Check out this branch or view preview
2. Navigate to https://deploy-preview-603--stanford-alumni.netlify.app/membership/register and sign in as `zguan`
3. Confirm the outline styles for the Membership Card and Membership Payment Card look correct
4. Review code 🏀 
- [ADAPTSM-163](https://stanfordits.atlassian.net/browse/ADAPTSM-163): DEV | Add focus state to Membership Card
[ADAPTSM-163]: https://stanfordits.atlassian.net/browse/ADAPTSM-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ADAPTSM-163]: …
> ADAPTSM-163 | @jdwjdwjdw | Update membership card focus state

- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/components/page-types/membershipFormPage/membershipFormPage.styles.js
- src/components/page-types/membershipFormPage/membershipInfoText.js
- src/components/page-types/membershipFormPage/membershipInfoText.styles.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.styles.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/components/page-types/membershipFormPage/relatedContactSelection.styles.js
-  fixup button state and bug
- Retroreview
1. Navigate to `membership/register`
2. Verify that the `Benefits of membership` button works
3. Verify that the disabled button is not keyboard/cursor accessible
4. Verify that the active button is keyboard/cursor accessible
5. Continue to the related contacts page at `membership/register/related-contacts`
6. Verify that the disabled button is not keyboard/cursor accessible
7. Verify that the active button is keyboard/cursor accessible
8. Review code 🌱 
- ADAPTSM-75
- ADAPTSM-167
> ADAPTSM-75 | @rebeccahongsf | fixup button state and bug

- src/components/cards/embedCard.js
> ADAPT-5573: Inject SUID for the for membed

- src/components/cards/membershipCard.js
-  style print version of digital card
- retroreview
1. Navigate to [`membership/membership-card`](https://deploy-preview-605--stanford-alumni.netlify.app/membership/membership-card/)
3. Click print card and verify that the print preview displays a 3x2" card (note: printer settings must have background enabled)
4. Review code 🤖 
- ADAPTSM-91
> ADAPTSM-91 | @rebeccahongsf | style print version of digital card

- src/styles/forms.css
- fixup radio and checkbox keyboard accessibility focus state
- retroreview
1. Navigate to [`membership/register`](https://deploy-preview-608--stanford-alumni.netlify.app/membership/register)
2. Continue to full payment form
3. Tab through to radio and checkbox
4. Confirm that there is a focus state
5. Review code 👀 
- ADAPTSM-162
- Thank you @yvonnetangsu for the hot tip 🔥
> ADAPTSM-162 | @rebeccahongsf | fixup radio and checkbox keyboard accessibility focus state

- src/components/page-types/membershipFormPage/membershipFormPage.styles.js
- fixup payment options bg gradient
- to be reviewed in membership branch pr
1. Navigate to `membership/register`
2. Select `myself` to view the payment options gradient and confirm that it matches figma
3. Review code
- ADAPTSM-75
> ADAPTSM-75 | @rebeccahongsf | fixup payment options bg gradient

- src/components/media/privateImage.js
- src/types/TripType.js
> Release: v3.1.0

- .github/workflows/release.yml
- package.json
- src/components/navigation/MainNav/userNavItems.jsx
> Release: v3.2.0

- src/api/travel-study/reg/internal-deposit.js
- remove deposit value for non-traveling caller
1. Navigate to https://travel-study-staff.kimbia.com/staff-registration?urlData=400490
2. Confirm that the deposit value of `$2000` appears only for the Traveler
3. Check out this branch and spin up your local
4. Navigate to https://adaptdemo.sites.stanford.edu/test-staff-form-local-registration
5. Search and select `Tasmania (400490)`
6. Verify that the deposit value of `$2000` appears only for the Traveler
7. Review code 👾 
- ADAPTTS-255
> ADAPTTS-255 | @rebeccahongsf | remove deposit value for non-traveling caller

- static/scripts/travel-study/gg-trip-form.js
- display deposit in USD
1. Checkout branch and spin up local
2. Navigate to https://adaptdemo.sites.stanford.edu/test-staff-form-local-registration
3. Search and select `Tasmania (400490)`
4. Verify that the deposit value in the trip summary sidebar appears as a dollar amount
5. Review code 👾 
- ADAPTTS-257
> ADAPTTS-257 | @rebeccahongsf | display deposit in USD

- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/membershipFormPage.js
- set myself as default
- Retroreview
1. Navigate to `/membership/form`
3. Verify that `Myself` is selected by default
4. Review code
- ADAPTSM-67
> ADAPTSM-67 | @rebeccahongsf | set myself as default

- static/scripts/travel-study/gg-trip-form.js
- increase max results 
- When possible for T/S testing
1. Check out this branch and run your local
2. Navigate to https://adaptdemo.sites.stanford.edu/test-staff-form-local-registration
3. Verify that 10 scrollable search results display when searching `202`
4. Review code 👾 
- ADAPTTS-252
> ADAPTTS-252 | @rebeccahongsf | increase max results 

- .github/workflows/release.yml
> Release 3.1.1

- src/api/auth/profile.js
- src/components/page-types/membershipFormPage/membershipInfoText.js
- src/utilities/sbLink.js
- adjust benefits of membership button to open in a new tab
1. Navigate to [`membership/register`](https://deploy-preview-641--stanford-alumni.netlify.app/membership/register)
3. Verify that upon clicking the `Benefits of membership` button, the link opens up in a new tab
4. Review code 👾 
- ADAPTSM-67
> ADAPTSM-67 | @rebeccahongsf | adjust benefits of membership button to open in a new tab

- static/_redirects
- Adds catch all domain redirect for alumni center 
- Review code for syntax
- Trust the rest
> ADAPT-5570 ADAPT-5571: Redirects for Alumni Center & Events

- static/_redirects
- Release: v3.1.3
- ADAPT-5570 ADAPT-5571: Redirects for Alumni Center & Events
> Release: v3.1.3

- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/components/page-types/membershipFormPage/membershipFullPaymentForm.js
- src/components/page-types/membershipFormPage/membershipInstallmentsForm.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/utilities/isAlum.js
- src/utilities/mocks/affiliations.js
- src/utilities/mocks/fullgg.js
- update promo/appeal code flow
- EOD Monday 4/24
1. Navigate to [`/membership/saacard` netlify preview](https://deploy-preview-651--stanford-alumni.netlify.app/membership/saacard/)
3. Confirm that a sample card appears
4. Navigate to [`/membership/form` netlify preview](https://deploy-preview-651--stanford-alumni.netlify.app/membership/register/)
5. Confirm that you are able to purchase a membership for yourself (the "Myself" card should be selectable)
6. Check out this branch
7. Add `MEGAPROFILE_MOCK = 'true'` to your `.env`
8. Spin up your local
9. Navigate to `/api/auth/profile`
10. Confirm that the affiliations and membership mock data appears as empty arrays
*Note: If you encounter a data error (e.g. `Cannot read properties of undefined (reading 'data')`), go to …
> ADAPTSM-175 | @rebeccahonsf | update promo/appeal code flow

- src/api/auth/profile.js
- add additional check for undefined data
- asap; I'd like to push this fix to PROD as well since it is blocking people from signing up for T/S things
1. Navigate to https://deploy-preview-652--stanford-alumni.netlify.app/
2. Log in as _... rebecca is looking for a test account with no contact data_
3. Verify that you are able to log in without any issues and view your data at https://deploy-preview-652--stanford-alumni.netlify.app/api/auth/profile
4. Review code 🪴
> NOJIRA | @rebeccahongsf | add additional check for undefined data

- src/api/auth/profile.js
- add additional check for megaprofile data
1. Review code
2. Remember to MERGE ONLY 👀
> Release: v3.1.4

- src/api/private-proxy.js
- add `authenticated` to the aff datasource
- retroreview
1. Navigate to [`/membership/saacard` netlify preview](https://deploy-preview-654--stanford-alumni.netlify.app/membership/saacard)
3. Verify that you must login to see the digital saa card
4. Check out this branch locally
5. Navigate to `profile.js`
6. Comment out the api calls for `affiliations` and `memberships`
7. Navigate to `fullgg.js` and make sure that `affiliations: []` is commented in.
8. Enable the local mockserver and spin up your local
9. Navigate to `/membership/saacard`
10. Verify that you must login to see the digital saa card
11. Review code 🤖 
- ADAPTSM-67
- ASM-79
> ADAPTSM-67 | @rebeccahongsf | add authenticated to the aff datasource

- src/components/page-types/membershipFormPage/membershipInfoText.js
- remove benefits button
- update textarea to richtext
- retroreview
1. Navigate to `/membership/register`
2. Verify that the benefits button no longer appears
3. Review code
- ADAPTSM-67
> ADAPTSM-67 | @rebeccahongsf | remove benefits button and update textarea to richtext

- .eslintignore
- .github/workflows/integration.yml
- cypress.config.ts
- cypress/e2e/root-0/index.cy.ts
- cypress/fixtures/example.json
- cypress/plugins/index.js
- cypress/results/test-results.xml
- cypress/support/commands.ts
- cypress/support/e2e.ts
- cypress/support/mockUsers.ts
- cypress/support/setup.ts
- package-lock.json
- package.json
- src/components/navigation/accountLinks.js
- tsconfig.json
- Automated testing
- 3
2. Make sure automated testing has set up correctly
> ADAPT-5584: automated testing

- src/styles/localist.css
> ADAPTOPS-125: One col no image localist styling

- static/_redirects
- Adds redirects for retiring Sierra camp
- End of sprint (Robocop)
- Low
1. Review code. 
2. Trust.
> ADAPT-5588: Sierra Camp redirects.

- src/styles/forms.css
- fixup installment payment review tally table
- asap
1. Navigate to `/membership/register`
2. Select Myself > Installment
3. Fill out first page of form and navigate to payment page
4. Verify that the installment payment review section appears like so: 
5. Navigate back to `/membership/register`
6. Test out Myself > Full payment
7. Fill out first page of form and navigate to payment page
8. Verify that the existing tally table styles has not been impacted by these changes
9. Review code 🪴 
- ADAPTSM-189
> ADAPTSM-189 | @rebeccahongsf | fixup installment payment review tally table

- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/utilities/mocks/fullprofile.js
- fixup membership content auth exp
- retro review
1. Navigate to [StoryBlok membership registration ](https://app.storyblok.com/#/me/spaces/184821/stories/0/0/224400868?env=PR+%23666)
2. Verify that the content authoring preview displays
3. Navigate to [`/membership/register`](https://deploy-preview-666--stanford-alumni.netlify.app/membership/register/)
4. Select Myself > Pay in Full
5. Verify that the email and phone number prefill correctly in the form
6. Review code 🤖
> NOJIRA | @rebeccahongsf | fixup membership content auth exp

- .eslintignore
- .github/workflows/integration.yml
- cypress.config.ts
- cypress/e2e/root-0/index.cy.ts
- cypress/fixtures/example.json
- cypress/plugins/index.js
- cypress/results/test-results.xml
- cypress/support/commands.ts
- cypress/support/e2e.ts
- cypress/support/mockUsers.ts
- cypress/support/setup.ts
- package-lock.json
- package.json
- src/components/navigation/accountLinks.js
- src/styles/localist.css
- static/_redirects
- tsconfig.json
- #660 
- #663 
- #662 
- EOD today or May 16 morning
1. Look at the diff and the preview
Note: I tested this on the PROD site - it looks like we can merge this in first (without locking the netlify preview), then the client can go in and modify the embedded event localist widget when they're ready. Merging in this code won't break anything on their existing site since the styling is added on top of the original stuff and is contained to this style of the widget (1-col) @sherakama
> Release v3.1.5

- src/styles/forms.css
- Add date picker specific styles
- Whenever
1. Navigate to `/travel-study/destinations/italy-test/register/form`
2. Continue to the reg form
3. Fill out form and add a new contact
4. Verify that the DOB field is now styled like so:
5. Review code 🐛 
- I saw this while briefly looking into `SR01324343 `
> nojira | @rebeccahongsf | add date picker specific styles

- src/components/page-types/membershipFormPage/membershipFullPaymentForm.js
- add optional chaining to the full payment form registration arr
- asap
1. Login as `zguan`
2. Navigate to https://deploy-preview-669--stanford-alumni.netlify.app/membership/join/form
3. Verify that you are redirected to https://deploy-preview-669--stanford-alumni.netlify.app/membership/join
4. Review code 🪴
> nojira | @rebeccahongsf | debugging redirect issue

- src/components/cards/membershipCard.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.styles.js
- src/styles/forms.css
- Adjust `selected` text for Payment options
- Add select field focus state
- Add cursor pointer for radio and checkboxes
- Update hardcoded color to cardinal red
- asap
1. Navigate to https://deploy-preview-671--stanford-alumni.netlify.app/membership/join
2. Verify that when selecting either full payment or installment, the ✔️ Selected text appears the same within the cards
3. Continue to form
4. Verify that upon tabbing to the select list, the gradient outline appears
5. Verify that upon hovering over the radio and checkboxes, the cursor pointer appears
6. Navigate to https://deploy-preview-671--stanford-alumni.netlify.app/membership/saacard
7. Verify the color (this is dependent on the membership for the test account)
8. Review code 👾
> ADAPTSM-74 | @rebeccahongsf | fixup form styles

- src/styles/forms.css
- Fix membership prod forms class
- asap pls :D
> Release v4.0.1

- static/_redirects
- Adds wildcard redirect for groups.alumni.stanford.edu
> ADAPT-5665: Redirect groups.alumni.stanford.edu.

- gatsby-node.js
- src/components/page-types/formPage/tripNotifyMe.js
- src/components/page-types/formPage/tripNotifyMe.styles.js
- add a check for unpublished trip to prevent breaking build
- asap
1. Navigate to 
- https://deploy-preview-678--stanford-alumni.netlify.app/travel-study/destinations/poland-2024
- https://deploy-preview-678--stanford-alumni.netlify.app/travel-study/destinations/poland-2024/notify
- https://deploy-preview-678--stanford-alumni.netlify.app/travel-study/destinations/china-2024
- https://deploy-preview-678--stanford-alumni.netlify.app/travel-study/destinations/china-2024/reserve
2. Verify that these pages do not exist (the trip pages are currently unpublished)
3. Review code
- ADAPT-5659
> ADAPT-5659 | @rebeccahongsf | add a check for unpublished trip to prevent breaking build

- gatsby-node.js
- src/components/auth/AuthIdleTimeoutOverlay.js
- src/components/layout/Modal/Modal.jsx
- src/components/layout/Modal/Modal.styles.js
- src/components/page-types/formPage/tripNotifyMe.js
- src/components/page-types/formPage/tripNotifyMe.styles.js
- Add conditional check for reg and trip notify me forms to prevent broken builds
- Fixup auth timeout modal positioning
- asap
- ADAPT-5659
- ADAPT-5589
> Release v4.0.4

- static/_redirects
- Reunion redirects
- Look at the code. 
- Thanks.
> ADAPT-5598: Add reunion redirects.

- static/_redirects
> ADAPT-5598: Add reunion.alumni domain.

- static/_redirects
- Redirects for Racial Justice
- End of the week
- Low
1. Review code for syntax errors
2. Trust in the way
> ADAPT-5783: Redirects for racial justice.

- src/components/page-types/registrationFormPage/interstitialPage.js
- src/utilities/filterRelationships.js
- src/utilities/mocks/fullprofile.js
- add filter for relationships
- when possible?
1. Check out this branch on local
2. Add `MEGAPROFILE_MOCK='true'` to your `.env`
3. Navigate to `/travel-study/destinations/scotland-2024/register`
4. Verify that only Teri and Ali show up as the only options. Meg should be excluded
5. Review code 👾 
- ADAPT-5679
> ADAPT-5679 | @rebeccahongsf | add filter for relationships

- src/components/page-types/formPage/tripNotifyMe.js
- Fix for back link
- When you can
- Normal
1. Navigate to a notify page and click the back to {trip name} link
> HOTFIX: Full slug.

- src/components/page-types/formPage/tripNotifyMe.js
- src/components/page-types/registrationFormPage/interstitialPage.js
- src/utilities/filterRelationships.js
- src/utilities/mocks/fullprofile.js
- Cut release for T/S relationships filter
1. Review code
- ADAPT-5679
> Release: v4.0.7

- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/utilities/giveGabVars.js
- squash email bug
- EOD Weds 7/26
1. Navigate to https://deploy-preview-691--stanford-alumni.netlify.app
2. Login as `kchrist499` (same pass as `zguan`; see ADAPT-5848)
3. Navigate to https://deploy-preview-691--stanford-alumni.netlify.app/membership/join
4. Select someone else and continue to related contacts page
5. Select either related contact or new contact then continue to form
6. Verify that the email `bharathp@other.stanford.edu` displays (this is the preferred email: "Other Email")
7. Navigate to https://deploy-preview-691--stanford-alumni.netlify.app/travel-study/destinations/finland-2022/finland-reg-form
8. Continue to form
9. Verify that the email `bharathp@other.stanford.edu` displays
10. Review code
- ADAPT-5848
> ADAPT-5848 | @rebeccahongsf | squash email bug

- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/utilities/giveGabVars.js
- Migrate to AWS
- Fixup email bug
> Release: v4.0.8

- src/components/components.js
- src/components/navigation/MegaMenu/megaMenu.js
- src/components/navigation/MegaMenu/megaMenu.styles.js
- src/components/navigation/MegaMenu/megaMenuCard.js
- src/components/navigation/MegaMenu/megaMenuLinkGroup.js
- src/components/navigation/MegaMenu/megaMenuLinkItem.js
- src/components/navigation/MegaMenu/megaMenuPanel.js
- src/components/navigation/MegaMenu/megaMenuPanel.styles.js
- build out mega menu components
- Retroreview!
- I'm rolling this into the megamenu dev branch so I can continue onwards with styling and adjusting the functionality.
1. Navigate to...
2. Verify that an unstyled menu of sort appears
3. Review code
- ADAPT-5901
> ADAPT-5901 | @rebeccahongsf | build out mega menu components

- src/components/navigation/MainNav/userNavItems.jsx
> ADAPT-5582: My Giving Link For Alumni

- src/components/navigation/MainNav/userNavItems.jsx
Release v4.0.9
Unhide WGH link.
> Release v4.0.9

- src/components/layout/Modal/Modal.styles.js
- src/components/navigation/MegaMenu/megaMenu.js
- src/components/navigation/MegaMenu/megaMenuCard.js
- src/components/navigation/MegaMenu/megaMenuCard.styles.js
- src/components/navigation/MegaMenu/megaMenuLink.styles.js
- src/components/navigation/MegaMenu/megaMenuLinkGroup.js
- src/components/navigation/MegaMenu/megaMenuLinkGroup.styles.js
- src/components/navigation/MegaMenu/megaMenuPanel.js
- src/components/navigation/MegaMenu/megaMenuPanel.styles.js
- theme mobile mega menu to use the same colors as the Giving site
1. Navigate to https://deploy-preview-696--stanford-alumni.netlify.app/
2. Verify that the mobile menu uses the same colors and spacing as Giving
3. Verify that the desktop menu is not impacted by these changes
4. Review code 🌱 
- [DS-173](https://stanford.atlassian.net/browse/DS-173)
> DS-173 | @rebeccahongsf | theme mobile mega menu

- netlify.toml
- src/components/page-types/membershipFormPage/MembershipCard.styles.js
- src/components/page-types/membershipFormPage/membershipCard.js
- src/components/page-types/membershipFormPage/membershipFormPage.js
- src/components/page-types/membershipFormPage/membershipFormPage.styles.js
- src/components/page-types/membershipFormPage/membershipInfoText.js
- src/components/page-types/membershipFormPage/membershipInfoText.styles.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.js
- src/components/page-types/membershipFormPage/membershipPaymentCard.styles.js
- src/components/page-types/membershipFormPage/relatedContactSelection.styles.js
- theme cards and interstitial pages
- retro review
Note: Some of the [mock's](https://www.figma.com/file/BfEeWa39C6xT6muvdkBXsw/Membership-2022%2F23?type=design&node-id=5022%3A24924&mode=design&t=XFf9zcvwh8M0B7Sx-1) spacing, text, and config does not accurately reflect the PROD version of the forms. Business has mentioned that they would like to keep everything (except the colors) the same as PROD.
1. Navigate to https://deploy-preview-711--stanford-alumni.netlify.app/membership/join
2. Verify that the type of registrant page contains the small colors as the [mock](https://www.figma.com/file/BfEeWa39C6xT6muvdkBXsw/Membership-2022%2F23?type=design&node-id=5022%3A24924&mode=design&t=XFf9zcvwh8M0B7Sx-1)
3. Select "Someone else" and continue to the related contacts interstitial page
4. …
> DS-94 DS-95 | @rebeccahongsf | theme cards and interstitial pages

- gatsby-browser.js
- src/components/embed/giveGabForm.js
- src/components/page-types/membershipFormPage/membershipFullPaymentForm.js
- src/components/page-types/membershipFormPage/membershipInstallmentsForm.js
- src/styles/forms.css
- src/styles/light-forms.css
- theme membership form
- retroreview
Note: Some of the [mock's](https://www.figma.com/file/BfEeWa39C6xT6muvdkBXsw/Membership-2022%2F23?type=design&node-id=5022%3A24924&mode=design&t=XFf9zcvwh8M0B7Sx-1) spacing, text, and config does not accurately reflect the PROD version of the forms. Business has mentioned that they would like to keep everything (except the colors) the same as PROD.
1. Navigate to https://deploy-preview-713--stanford-alumni.netlify.app/membership/join
2. Navigate to the form page and verify that the form theme/colors matches the [mock](https://www.figma.com/file/BfEeWa39C6xT6muvdkBXsw/Membership-2022%2F23?type=design&node-id=5022%3A24924&mode=design&t=XFf9zcvwh8M0B7Sx-1)
3. Review code 🐱
- [DS-45](https://stanford.atlassian.net/browse/DS-45)
- …
> DS-93 | @rebeccahongsf | theme membership form

- src/components/components.js
- src/components/layout/Modal/Modal.styles.js
- src/components/navigation/MegaMenu/megaMenu.js
- src/components/navigation/MegaMenu/megaMenu.styles.js
- src/components/navigation/MegaMenu/megaMenuCard.js
- src/components/navigation/MegaMenu/megaMenuCard.styles.js
- src/components/navigation/MegaMenu/megaMenuLink.styles.js
- src/components/navigation/MegaMenu/megaMenuLinkGroup.js
- src/components/navigation/MegaMenu/megaMenuLinkGroup.styles.js
- src/components/navigation/MegaMenu/megaMenuLinkItem.js
- src/components/navigation/MegaMenu/megaMenuPanel.js
- src/components/navigation/MegaMenu/megaMenuPanel.styles.js
- src/components/navigation/userHeaderIcon.js
- [DS-40 |](https://github.com/SU-SWS/saa_alumni/commit/4bd06772e6531067d43974ea9f5099a1f2831036) @rebeccahongsf [| Alumni Homesite Mega Menu](https://github.com/SU-SWS/saa_alumni/commit/4bd06772e6531067d43974ea9f5099a1f2831036)
- asap
1. Navigate to https://dev--stanford-alumni.netlify.app/test/rebecca/mega-menu-test
2. Verify that the mega menu is appear as expected 
3. Review code 🌵
> Release v4.1.0

- src/styles/forms.css
- src/styles/light-forms.css
- fixup stripe btn styling
- We'll have Business review
Requirements:
- Have Google Pay enabled on Chrome
1. Navigate to https://deploy-preview-721--stanford-alumni.netlify.app/membership/join
2. Fill out form and get to the payment page
3. Verify that the Google Pay button appears 
4. Review code
- DS-256
> DS-256 | @rebeccahongsf | fixup stripe btn styling

- src/styles/forms.css
- src/styles/light-forms.css
- fixup stripe btn styling
- We'll have Business review
Requirements:
- Have Google Pay enabled on Chrome
1. Navigate to https://deploy-preview-722--stanford-alumni.netlify.app/membership/join
2. Fill out form and get to the payment page
3. Verify that the Google Pay button appears 
4. Review code
- DS-256
> DS-256 | @rebeccahongsf | fixup google pay btn

- src/styles/forms.css
- DS-376 Fixup T/S Payment Btn
> Release v4.2.1

- src/components/page-types/membershipFormPage/membershipFormPage.js
- limit text input to 10 char
- asap
1. Navigate to https://deploy-preview-733--stanford-alumni.netlify.app/membership/join
3. Verify that you cannot input more than 10 digits into the promo code field
4. Review code 👁️ 
- [DS-392](https://stanford.atlassian.net/browse/DS-392)
> DS-392 | @rebeccahongsf | limit text input to 10 char

- src/components/page-types/membershipFormPage/membershipFormPage.js
- Add text limit to promo code on membership form
- Add help text for accessibility
> Release v4.2.2

- src/api/membership/payment/[...history].js
- src/components/components.js
- src/components/embed/dynaScript.js
- src/components/embed/giveGabForm.js
- src/components/page-types/lightFormPage/lightFormPage.js
- src/utilities/givegab/GiveGabNonce.js
- DS-264 | add light form page block to SB and scaffold component
- DS-265 | build out GG Nonce fetch
- retroreview 
I might just roll this in and continue onto styling and megaprofile updates. Please feel free to request changes and share thoughts! I will make sure to implement any feedback in a future PR.
1. Navigate to https://deploy-preview-738--stanford-alumni.netlify.app/membership/payment-history
2. Verify that a payment form loads
3. Review code
- DS-264
- DS-265
> DS-264 | @rebeccahongsf | add light form page component

- static/_redirects
- DS-413: Associates Designees redirect
> DS-413: Associates Designees redirect

- static/_redirects
- DS-413: Associates Designees redirect
> Release: v4.2.3

- src/components/embed/giveGabForm.js
- src/components/page-types/formPage/formPage.js
- src/components/page-types/lightFormPage/lightFormPage.js
- src/components/page-types/lightFormPage/lightFormPage.styles.js
- src/components/page-types/membershipFormPage/membershipFullPaymentForm.js
- src/components/page-types/membershipFormPage/membershipInstallmentsForm.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/styles/light-forms.css
- src/utilities/mocks/fullprofile.js
- theme self service portal
Note: I'll be circling back in DS-271 and DS-272 to adjust the form styles since there are some GiveGab issues with the data not rendering for single installment plans.
- retroreview 
1. Navigate to https://deploy-preview-744--stanford-alumni.netlify.app/membership/payment-history
3. Verify that the widget appears in a card, similar to the Membership form
4. Navigate to https://deploy-preview-744--stanford-alumni.netlify.app/membership/payment-update
5. Verify that the widget appears in a card, similar to the Membership form
6. Review code
- DS-270
- DS-271
- DS-272
> DS-270 | @rebeccahongsf | theme self service portal

- src/api/auth/profile.js
- src/components/page-types/lightFormPage/lightFormPage.js
- src/utilities/mockServer.js
- src/utilities/mocks/fullprofile.js
- src/utilities/mocks/index.js
- src/utilities/mocks/memberships.js
- fetch payment ref id from mock membership
- correctly setup memberships mock
**Note:** Widget might render without data due to known GiveGab bug.
1. Checkout branch on your local
2. Enable mockserver by adding `MEGAPROFILE_MOCK='true'` to your .env
3. Navigate to `/membership/payment-history`
4. Verify that the widget appears in a card, similar to the Membership form
5. Navigate to `/membership/payment-update`
8. Verify that the widget appears in a card, similar to the Membership form
9. Review code
1. Navigate to https://deploy-preview-746--stanford-alumni.netlify.app/membership/payment-history
2. Verify that a payment id error appears
3. Navigate to https://deploy-preview-746--stanford-alumni.netlify.app/membership/payment-update
4. Verify that a payment id error …
> DS-267 | @rebeccahongsf | fetch payment ref id and correctly setup memberships mock

- src/components/partials/htmlHead.js
- remove meta tag containing application name
1. Navigate to https://deploy-preview-751--stanford-alumni.netlify.app/
2. Inspect and verify that the `<meta name="application-name" content="Stanford University"/>` no longer appears
3. Review code
- DS-13
> DS-13 | @rebeccahongsf | remove meta tag containing application name

- src/components/page-types/lightFormPage/lightFormPage.js
- fixup nonce error
- Retroreview. Rolling this in so I can have a working demo for tomorrow's meeting with membership. I'll be implementing the error use cases in a separate PR and will roll up any feedback into that work. Thank you! :D
1. Checkout branch on your local
2. Enable mockserver
3. Navigate to /membership/payment-history
4. Verify that the self-service portal loads
5. Navigate to membership/payment-update
6. Verify that the self-service portal loads
7. Review code
- DS-265
> DS-265 | @rebeccahongsf | fixup nonce error

- src/components/partials/htmlHead.js
- DS-13 | @rebeccahongsf | remove mega tag containing application name
> Release v4.2.4

- static/_redirects
> ADVPS-12724: Restore Register Redirect

- static/_redirects
> Release: v4.3.2

- package-lock.json
- package.json
- src/utilities/hasRichText.js
- src/utilities/richTextRenderer.js
- #780 
- EOD Dec 15
- 6
1. Look at code diff
> Release v4.3.4

- src/components/composite/hero.js
- Add x-small size to hero banner
> Release: v4.3.6

- package.json
- Update version within package.json
- Whenever
> nojira | @rebeccahongsf | Update version within package.json

- netlify/edge-functions/protected-content.js
Release v4.3.12
Includes:
- Search/hash edge function fix: #822
> Release v4.3.12

- src/components/embed/giveGabForm.js
- src/components/page-types/lightFormPage/lightFormPage.js
- src/styles/light-forms.css
- src/utilities/mocks/memberships.js
- QA fixes (see DS-170)
- retro, we'll have the clients review the front-end
- DS-170
> DS-170 | @rebeccahongsf | QA fixes

- src/components/page-types/registrationFormPage/registrationFormPage.js
- static/scripts/travel-study/gg-trip-form.js
- fix T/S Cancellation policy link
- 7
2. Navigate to a travel study reserve form
3. Click on `Cancellation Policy` link and make sure it only opens the correct cancelation policy page (`#cancellation-policy`)
4. Review [ticket](https://stanford.atlassian.net/browse/DS-601) and code and make sure everything works as expected
> DS-601: fix T/S Cancellation policy link

- src/components/page-types/registrationFormPage/registrationFormPage.js
- static/scripts/travel-study/gg-trip-form.js
> Release: v4.3.14

- src/components/page-types/associatesDirectoryPage/Directory/AssociateList.jsx
- src/components/page-types/associatesDirectoryPage/Directory/TabHeader.jsx
- src/components/page-types/associatesDirectoryPage/Directory/Tabs.jsx
Release v4.3.15
Includes:
- DS-629 | #835 : A11y-related tab fixes
> Release v4.3.15

- src/components/identity/localFooter.js
- src/components/navigation/linkGroup.js
Release v4.3.16
Includes:
- Update footer code to accommodate new footer content: #839
> Release v4.3.16

- src/components/page-types/associatesDirectoryPage/Directory/AssociateList.jsx
- src/components/simple/linkList.js
Release v4.3.17
Includes:
- Hiding empty ULs: #842
> Release v4.3.17

- cypress/e2e/1-perks/online-database.cy.ts
- cypress/e2e/2-travel-study/destinations-filter.cy.ts
- src/components/simple/Chip/Chip.jsx
- src/components/simple/Chip/Chip.styles.js
- src/components/simple/FilterCheckbox/FilterCheckbox.jsx
- Fix a couple tests
- Soon
- Low
1. Look at changes/tests
> Nojira | @ericbakenhus | Adjust online db test

- cypress/e2e/1-perks/online-database.cy.ts
- cypress/e2e/2-travel-study/destinations-filter.cy.ts
- netlify.toml
- src/api/membership/payment/[...history].js
- src/components/components.js
- src/components/embed/dynaScript.js
- src/components/embed/giveGabForm.js
- src/components/page-types/formPage/formPage.js
- src/components/page-types/lightFormPage/lightFormPage.js
- src/components/page-types/lightFormPage/lightFormPage.styles.js
- src/components/page-types/membershipFormPage/membershipFullPaymentForm.js
- src/components/page-types/membershipFormPage/membershipInstallmentsForm.js
- src/components/page-types/registrationFormPage/registrationFormPage.js
- src/components/simple/Chip/Chip.jsx
- src/components/simple/Chip/Chip.styles.js
- src/styles/light-forms.css
- src/utilities/givegab/GiveGabNonce.js
- src/utilities/mocks/memberships.js
- #779 
- #824 
- asap, please 🙏
> Release v4.4.0

- src/components/cards/membershipCard.js
- src/components/page-types/gsbCardPage.js
- DS-469: Update print version of digital membership card for SAA and GSB
- 3
2. Navigate to `/membership/saacard/` and `/membership/gsbcard/`
3. Make sure that printed card shows the card color correctly (without updating any additional setting in the browser's print configuration)
> DS-469: Update print version of digital membership card for SAA and GSB

- src/components/components.js
- src/components/content-types/synchronized-event/synchronizedEvent.js
- Stub synchronized event component (so _something_ shows up in the editing UI)
- Low
2. In Storyblok (DEV), check out a test event: `/events/sync/test`
3. In Storyblok (DEV), check out the Synchronized Event content type
- DS-679
> DS-679 | @ericbakenhus | Stub synchronized event component

- .github/workflows/merge-to-events-discovery.yml
- Merge `dev` to `events-discovery`
- Soon
- 5
1. Make sure that the new workflow merge `dev` branch to `events-discovery` after each successful PR merge
> NO-JIRA: Merge dev to events-discovery

- .github/workflows/merge-to-events-discovery.yml
- netlify/functions/handle-deploy-background.ts
- package-lock.json
- package.json
- src/components/navigation/MegaMenu/megaMenu.js
- src/types/storyblok/api/SBWebhookType.ts
- src/utilities/mergeEventOverrides.js
Release v4.4.2
Includes:
- events-discovery merge action: #854 
- Webhook background function: #851 
- Mega Menu option to sub pages on Alumni Homesite: #853
> Release v4.4.2

- netlify/functions/handle-deploy-background.ts
- src/utilities/synchronizedEvents.js
- Add fields needed for Algolia config
- High
- DS-687
> DS-687 | @ericbakenhus | Add generated fields for Algolia config

- netlify/functions/handle-deploy.ts
- Switch deploy handler to normal function
- ASAP/Retro
- High
- DS-762
> DS-762 | @ericbakenhus | Use normal function for deploy handler

- src/utilities/synchronizedEvents.js
- Removes generated description text
- Retro
- High
- DS-687
> DS-687 | @ericbakenhus | Remove description text

- package.json
- src/utilities/synchronizedEvents.js
- Storyblok represents number fields as strings in JSON (WHY?!?) so we need to convert lat and long values for Algolia
- Soon/Retro
- Medium
- DS-687
> DS-687 | @ericbakenhus | Fix lat and long

- gatsby-config.js
Note: merging to dev/prod so it's ready to go when we launch
- Exclude sync events from the sitemap
- Low
2. Look at sitemap for the deploy preview
- DS-694
> DS-694 | @ericbakenhus | Exclude events from sitemap

- gatsby-node.js
- package-lock.json
- package.json
- src/components/Sa11yInit.js
- src/components/Sa11yInit.tsx
- src/pages/editor.js
- Add sa11y to `/editor` page
- 4
2. Navigate to `/editor` page (copy the url parameters from Storyblok dev space)
3. Verify that `sa11y` works as expected on `editor` page
> DS-653: Add sa11y to `/editor` page

- package-lock.json
- package.json
- src/components/events-discovery/components/Chips/ChipsComponent.jsx
- src/components/events-discovery/components/DateFilter/DateFilter.jsx
- src/components/events-discovery/components/DateFilter/RadioInput.jsx
- src/components/events-discovery/components/DateFilter/index.js
- src/components/events-discovery/components/Drawer/Drawer.jsx
- src/components/events-discovery/components/Facets/FacetComponent.jsx
- src/components/events-discovery/components/Facets/useFacets.js
- src/components/events-discovery/components/FilterAccordion/FilterAccordion.jsx
- src/components/events-discovery/components/FilterAccordion/SubfilterAccordion.jsx
- src/components/events-discovery/components/FilterAccordion/index.js
- src/components/events-discovery/components/Filters/DesktopFilter.jsx
- src/components/events-discovery/components/constants.js
- src/components/events-discovery/eventsDiscovery.jsx
- Date/calendar filters
- 🤷 
- Low
1. Check out this branch or deploy preview
2. Navigate to [/events/discovery](https://deploy-preview-875--stanford-alumni.netlify.app/events/discovery/)
4. Mess with the date options
5. Verify events are being filtered correctly
- NOTE: The filters are currently based on local system timezone, but the cards themselves display PT dates/times. Timezone information is being added to the source data to allow for correct card timezone display in a future PR.
- DS-705
- DS-706
> DS-705, DS-706 | Date/calendar filter

- src/components/events-discovery/components/DateFilter/DateFilter.jsx
- src/components/events-discovery/components/Facets/FacetComponent.jsx
- src/components/events-discovery/components/Facets/FacetCtx.jsx
- src/components/events-discovery/components/Facets/useFacets.js
- src/components/events-discovery/components/FilterAccordion/FilterAccordion.jsx
- src/components/events-discovery/components/FilterAccordion/SubfilterAccordion.jsx
- src/components/events-discovery/components/Filters/DesktopFilter.jsx
- src/components/events-discovery/components/LocationFilter/LocationFilter.jsx
- src/components/events-discovery/components/LocationFilter/OnlineOptionsSubfilter.jsx
- src/components/events-discovery/eventsDiscovery.jsx
- Refactor useFacets
- Adds nested filter
- Adds online options filter
- 🤷 
- Low
1. Check out this branch or use the deploy preview
2. Navigate to [/events/discovery](https://deploy-preview-875--stanford-alumni.netlify.app/events/discovery/)
3. Verify the Online options filter is working
4. Verify all the accordions and new sub accordion is working as expected
- DS-708
- DS-704
> DS-704, DS-708 | @ericbakenhus | Nested filters and online options facet

- gatsby-node.js
- Add synchronized event type to list of excluded types for page rendering
- Low
2. Verify no pages exist for any published test events (e.g. https://deploy-preview-878--stanford-alumni.netlify.app/events/discovery/test)
- DS-695
> DS-695 | @ericbakenhus | Exclude synchronized events from build

- static/_redirects
- Adds some magazine redirects
- End of sprint (or before 7/12)
- Low
1. Look at redirects
2. Make sure they redirect on the deploy preview
- DS-766
> DS-766 | @ericbakenhus | Magazine redirects

- gatsby-node.js
- static/_redirects
Release v4.4.5
Includes:
- Exclude Synchronized events from build: #878 
- New Magazine redirects: #869
> Release v4.4.5

- src/components/content-types/synchronized-event/synchronizedEvent.js
- src/components/events-discovery/components/Event/Event.jsx
- src/components/events-discovery/components/Event/EventHeading.jsx
- src/components/events-discovery/components/Facets/FacetCtx.jsx
- src/components/events-discovery/components/Filters/DesktopFilter.jsx
- src/components/events-discovery/components/Hit/Hit.jsx
- src/components/events-discovery/components/LocationFilter/InternationalSubfilter.jsx
- src/components/events-discovery/components/LocationFilter/LocationFilter.jsx
- src/components/events-discovery/components/LocationFilter/UsSubfilter.jsx
- src/components/events-discovery/components/LocationFilter/index.js
- src/components/events-discovery/components/SubjectFilter/GeneralTagsFilter.jsx
- src/components/events-discovery/components/SubjectFilter/IdentityTagsFilter.jsx
- src/components/events-discovery/components/SubjectFilter/SubjectFilter.jsx
- src/components/events-discovery/components/SubjectFilter/index.js
- src/components/events-discovery/components/constants.js
- Adds General and Diversity/Identity tag filters
- Adds US and International region filters
- 🤷 
- Low
1. Check out this branch or use the deploy preview
2. Navigate to [/events/discovery](https://deploy-preview-882--stanford-alumni.netlify.app/events/discovery/)
3. Verify that the US and International filters (inside Location) work as expected
4. Verify that the General and Diversity/Identity filters (inside Subject) work as expected
- DS-709
- DS-710
- DS-712
> DS-709, DS-710, DS-712 | @ericbakenhus | Add tag and region filters

- src/components/events-discovery/components/Chips/Chip.jsx
- src/components/events-discovery/components/DateFilter/DateFilter.jsx
- src/components/events-discovery/components/Event/Event.jsx
- src/components/events-discovery/components/Event/EventContent.jsx
- src/components/events-discovery/components/StatusHeader/StatusHeader.jsx
- src/components/events-discovery/eventsDiscovery.jsx
- Add results count
- Adjust flow of surrounding elements
- Retro
- Low
1. Look at the [deploy preview](https://deploy-preview-884--stanford-alumni.netlify.app/events/discovery/)
2. Verify that the results count is visible above the events
3. Verify there is visibly hidden additional page-related data for screen readers
- DS-721
> DS-721 | @ericbakenhus | Add results count

- package-lock.json
- package.json
- src/components/events-discovery/components/Chips/ChipsComponent.jsx
- src/components/events-discovery/components/FilterAccordion/FilterAccordion.jsx
- src/components/events-discovery/components/Filters/DesktopFilter.jsx
- src/components/events-discovery/components/SearchBar/SearchBar.jsx
- src/components/events-discovery/components/SearchBar/index.js
- src/components/events-discovery/components/constants.js
- src/components/events-discovery/eventsDiscovery.jsx
- src/hooks/useDebouncedValue.js
- Add search bar with autocomplete (mobile search will be handled in DS-716)
- Retro
- Low
3. Verify the search bar allows for searching by title
4. Verify suggestions are shown below the input after a value is typed
5. Verify the search button works
6. Verify a chip is shown when a search query is active
7. Verify a clear button is shown below the search input when a query is active
- DS-714
> DS-714 | @ericbakenhus | Search bar with autocomplete

- src/components/events-discovery/components/Event/Event.jsx
- src/components/events-discovery/components/Event/EventContent.jsx
- src/components/events-discovery/components/Hit/Hit.jsx
- Adds select to switch time zones for each event
- Retro
- Low
3. Verify that the time zone on each event is a dropdown _if the event's time zone is different than your system's time zone_
4. Verfiy that the time zone on each event is simple text _if the event's time zone is the same as your system's time zone_
5. Verify that changing an event's time zone changes the start/end datetimes to match
- DS-793
> DS-793 | @ericbakenhus | Allow switching timezones on events

- src/components/events-discovery/components/Event/EventContent.jsx
- Just some styles tweaks for the time zone select (bump the font size and allow for clicking on the chevron)
- Retro
- Low
3. Verify the time zone select field looks fine
- DS-793
> DS-793 | @ericbakenhus | Style tweaks

- src/components/events-discovery/components/Event/Event.jsx
- src/components/events-discovery/components/Event/EventHeading.jsx
- src/components/events-discovery/components/Hit/Hit.jsx
- Adds query highlighting for event titles
- Retro
- Low
3. Search for something
4. Verify any matches in titles are highlighted
- DS-722
> DS-722 | @ericbakenhus | Add title highlighting

- src/components/events-discovery/components/Event/EventContent.jsx
- Switches from `MST (Same as PDT)` to `MST/PDT`
- Removes time zones for multi-day events
- Retro
- Low
3. Verify the stuff and things
- DS-793
> DS-793 | @ericbakenhus | Tweak timezone format

- src/components/events-discovery/components/Filters/DesktopFilter.jsx
- Swap filter order
- Retro
- Low
3. Verify the filter order is Date, Location, Format, Subject
- DS-800
> DS-800 | @ericbakenhus | Misc QA fixes

- src/components/events-discovery/components/Chips/Chip.jsx
- src/components/events-discovery/components/Event/EventContent.jsx
- src/components/events-discovery/components/EventsPerPage/EventsPerPage.jsx
- src/components/events-discovery/components/EventsPerPage/index.js
- src/components/events-discovery/components/Facets/FacetCtx.jsx
- src/components/events-discovery/components/Facets/FacetList.jsx
- src/components/events-discovery/eventsDiscovery.jsx
- Adds events per page selector
- Retro
- Low
3. Verify there is an events per page selector and that it works as expected
4. Verify all the options (i.e. more than 10) can be see for each filter that contains a list of refinements (e.g. subject)
- DS-800
> DS-800 | @ericbakenhus | Results per page

- src/components/events-discovery/components/Facets/FacetCtx.jsx
- src/components/events-discovery/components/Facets/FacetList.jsx
- src/components/events-discovery/components/Filters/DesktopFilter.jsx
- src/components/events-discovery/components/LocationFilter/LocationFilter.jsx
- Change one label
- Use context data for labels
- Whenever/retro
- Low
3. Verify that the subject filter is labeled "Subject"
4. Verify all the other filters are still correctly labeled
- DS-800
> DS-800 | @ericbakenhus | Adjust labels

- netlify/functions/event-import-background.mts
- Why event have a library to interact with the API when I have to specific the method and URL anyways? 🙃 
- 🤷 
- High
> Nojira | @ericbakenhus | Update SB urls

- netlify/functions/event-import-background.mts
- Adjusting some old event handling and fixing an id
- Whenever
- High
> Nojira | @ericbakenhus | Adjust old story handling

- src/components/events-discovery/components/Facets/FacetList.jsx
- src/components/events-discovery/components/Facets/MobileFacetList.jsx
- src/components/events-discovery/components/LocationFilter/LocationFilter.jsx
Release v5.0.1
Includes:
- Events show more facets toggle: #905 
- Events location reset button: #920
> Release v5.0.1

- netlify/functions/trigger-event-import.mts
- Remove context check in scheduled function
- Retro
- High
- DS-800
> DS-800 | @ericbakenhus | No context var for scheduled functions

- netlify/functions/trigger-event-import.mts
Release v5.0.2
Includes:
- Tweaking the events scheduled function to actually run: #923
> Release v5.0.2

- src/components/navigation/MegaMenu/megaMenuTopLevelLinkItem.js
> Release: v5.0.3

- netlify/functions/event-import-background.mts
- netlify/functions/trigger-event-import.mts
- src/utilities/synchronizedEvents.js
- Fix import function URL in scheduled function
- Trigger an update if region is missing on existing events
- ASAP/Retro
- High
> Nojira | @ericbakenhus | Fix event import URL

- netlify/functions/event-import-background.mts
- src/utilities/synchronizedEvents.js
- Fix google key
- Remove region comparison check
- ASAP/Retro
- High
> Nojira | @ericbakenhus | Fix maps key

- netlify/functions/event-import-background.mts
- netlify/functions/trigger-event-import.mts
- src/components/events-discovery/components/Event/EventContent.jsx
- src/components/events-discovery/components/EventsPerPage/EventsPerPage.jsx
- src/components/events-discovery/components/LocationFilter/LocationTabPanelCity.jsx
- src/components/partials/header.js
- src/utilities/synchronizedEvents.js
Release v5.0.4
Includes:
- Events A11y tweaks: #919 
- Events scheduled sync fix: #942 
- Events regions fix: #943
> Release v5.0.4

- src/utilities/dates.js
- src/utilities/transformDate.js
- Swap all date utility function to use Luxon
- 🤷 
- Medium
2. Check out this branch
3. Make sure trip dates still look correct, for example:
- Go to one of the trips (e.g. https://deploy-preview-951--stanford-alumni.netlify.app/travel-study/destinations/finland-2022/), get to the GiveGab form, and check the variables set on Window to make sure the dates look alright
- DS-883
> DS-883 | @ericbakenhus | Use Luxon for all the things

- src/utilities/dates.js
- src/utilities/transformDate.js
Release v5.0.5
Includes:
- Swapping to Luxon for all date parsing: #951
> Release v5.0.5

- src/components/events-discovery/components/Facets/FacetList.jsx
- Allow wrapping for filter text
- Whenever
- Low
2. Do the things and stuff
- DS-800
> DS-800 | @ericbakenhus | Filter wrapping fix

- src/components/events-discovery/components/DateFilter/RadioInput.jsx
- Fixes a text color change that slipped through in a previous PR
- Retro/now?
- Medium
1. Looking at the code is fine
> Nojira | @ericbakenhus | Fix date filter radio button text color

- src/components/events-discovery/components/DateFilter/RadioInput.jsx
Release v5.1.2
Includes:
- Event date filter color fix: #964
> Release v5.1.2

- src/components/events-discovery/components/Facets/MobileFacetList.jsx
- src/components/events-discovery/components/Filters/MobileParentFilter.jsx
- Dangit
- Dangit
- Dangit
1. Dangit
> Nojira | @ericbakenhus | Fix mobile filter text color

- src/components/events-discovery/components/Facets/MobileFacetList.jsx
- src/components/events-discovery/components/Filters/MobileParentFilter.jsx
Release v5.1.3
Includes:
- Mobile filter text color fixes: #966
> Release v5.1.3

- src/components/events-discovery/components/Pagination/Pagination.jsx
- src/components/events-discovery/components/StatusHeader/StatusHeader.jsx
- src/components/navigation/MegaMenu/megaMenuLink.styles.js
- src/components/navigation/MegaMenu/megaMenuTopLevelLinkItem.js
Release v5.1.4
Includes:
- Pagination scroll for events: #971 
- Top level external link arrow color fix: #968
> Release v5.1.4

- netlify/functions/handle-deploy.mts
- src/components/events-discovery/components/Facets/FacetList.jsx
- src/components/events-discovery/components/SearchBar/MobileSearchBar.jsx
- src/components/events-discovery/components/SearchBar/SearchBar.jsx
- src/components/events-discovery/eventsDiscovery.jsx
- Adds same base filter used by the results to the search bar
- This will prevent expired events and events outside the current date filter range from being suggested
- (Tossed in) Fix deployment function so it's able to get unpublished stories in order to remove them from Algolia
- Now/retro
- High
3. Search for Hong Kong
4. Verify there are no suggestions
- DS-987
> DS-987 | @ericbakenhus | Filter search suggestions based on full results filter

- src/api/travel-study/index.js
- src/api/travel-study/reg/internal-deposit.js
- src/api/travel-study/reg/post-extension.js
- src/api/travel-study/reg/pre-extension.js
- src/api/travel-study/reg/room-category.js
- src/api/travel-study/reg/trip-deposit.js
- src/api/travel-study/trips/index.js
- src/utilities/getAllTrips.js
- Just some clean up and revising while I was debugging
- This doesn't fix anything. Just changes things.
- Whenever
-  Not
1. Visit each of the APIs and ensure they are returning properly formatted data
2. https://deploy-preview-969--stanford-alumni.netlify.app/api/travel-study/reg/internal-deposit
3. https://deploy-preview-969--stanford-alumni.netlify.app/api/travel-study/reg/post-extension
4. https://deploy-preview-969--stanford-alumni.netlify.app/api/travel-study/reg/pre-extension
5. https://deploy-preview-969--stanford-alumni.netlify.app/api/travel-study/reg/room-category
6. https://deploy-preview-969--stanford-alumni.netlify.app/api/travel-study/reg/trip-deposit
7. https://deploy-preview-969--stanford-alumni.netlify.app/api/travel-study/trips/
8. …
> DS-882: Clean up TS reg api.

- netlify/functions/handle-deploy.mts
- Actually fix deploy issues
- Revert bad options change
- Move a filter that was preventing expired stories from being removed from Algolia
- Soon/Retro
- High
1. Look at code?
> Nojira | @ericbakenhus | Fix deploy

- netlify/functions/handle-deploy.mts
- src/api/travel-study/index.js
- src/api/travel-study/reg/internal-deposit.js
- src/api/travel-study/reg/post-extension.js
- src/api/travel-study/reg/pre-extension.js
- src/api/travel-study/reg/room-category.js
- src/api/travel-study/reg/trip-deposit.js
- src/api/travel-study/trips/index.js
- src/components/events-discovery/components/Facets/FacetList.jsx
- src/components/events-discovery/components/SearchBar/MobileSearchBar.jsx
- src/components/events-discovery/components/SearchBar/SearchBar.jsx
- src/components/events-discovery/eventsDiscovery.jsx
- src/utilities/getAllTrips.js
Release v5.1.5
Includes:
- Limit event search suggestions based on overall date filters: #973 
- Fix deploy script to correctly handle unpublished events:
- #973
- #975
- Clean up TS API: #969
> Release v5.1.5

- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/components/page-types/registrationFormPage/interstitialPage.js
- src/utilities/transformDate.js
- src/utilities/userProfile.js
- Fix DOB parsing function
- Now
- High
2. Navigate to a T/S trip (e.g. https://deploy-preview-987--stanford-alumni.netlify.app/travel-study/destinations/finland-2022/)
3. Click reserve to start the form
4. Click through to the next page
5. Verify it does not ask for a birth date:
6. (optionally) Inspect the window object, find the `su_dob` property, and verify that it looks like a US format date
- DS-1011
> DS-1011 | @ericbakenhus | Fix date parsing function

- src/components/page-types/membershipFormPage/relatedContactSelection.js
- src/components/page-types/registrationFormPage/interstitialPage.js
- src/utilities/transformDate.js
- src/utilities/userProfile.js
Release v5.1.7
Includes:
- Date parsing fix: #987
> Release v5.1.7

- src/components/events-discovery/components/Event/EventContent.jsx
Release v5.1.8
Includes:
- Event time zone fix: #990
> Release v5.1.8
