SU-SWS/saa_alumni

src/components/partials/htmlHead.js
src/components/simple/linkList.js
src/utilities/richTextRenderer.js
src/utilities/sbLink.js
src/utilities/transformImage.js
static/_redirects

- Add asset url for PDFs and Images
- Note: File changes overlap with PR #68. I can manually resolve them once that PR is merged.
- July 23
- 7
2. Review locally at `/test/rebecca/asset-url-test/` or on [Netlify Preview](https://deploy-preview-75--stanford-alumni.netlify.app/test/rebecca/asset-url-test/)
- All asset URLs (i.e. pdfs, images, etc) should now be using `https://assets.stanford.edu/`
- This should work within the WYSIWYG, CtaLinks, and any other components that utilize the asset link/image field.
- [ADAPT-2948](https://stanfordits.atlassian.net/browse/ADAPT-2948)

ADAPT-2948 Add asset url

---

src/components/page-types/searchPage.js

- Added a helper text for when the search input in submitted empty.
- 1
1. Navigate to /search/
2. Check out the functionality on the search modal
- Other PRs
- [Browserstack](https://live.browserstack.com/dashboard) and link to …

ADAPT-2673: Add Empty search message to the search page

---

src/components/page-types/searchPage.js

- Refactors implementation of Search facets to allow for selecting multiple values.
- This may also fix ADAPT-3116
- By end of next week (August 13th). 
- How critical is this PR on a 1-10 scale? 
Probably around a 7-8. 
1. Just visit /search in the preview environment, and test out the new filter behaviors.
- https://stanfordits.atlassian.net/browse/ADAPT-3115
- https://stanfordits.atlassian.net/browse/ADAPT-3116
The primary challenge is that after you update the search filters, the updated response from Algolia will remove all of the facet values except for the ones you selected. 
However, Algolia does show the multiple-select behavior in some of their demos, so I was able to do a little bit of reverse engineering to …

ADAPT-3115: Refactored facets implementation to allow for multiple values.

---

src/components/cards/embedCard.js

- Fixes render-breaking error on builds when using Embed Card component.
- By end of sprint.
- 9/10 - Without this fix, white screen of death is seen when using embed card component.
1. Visit a page that is using the Embed Card component, such as /test/yvonne/test-home-embed-error/
- https://stanfordits.atlassian.net/browse/ADAPT-3103
- The issue had something to do with the ID generator library not behaving as expected on static builds.
(I wasn't able to pin it down 100%, but I think what was happening was that it was re-generating the ID during hydration causing a mismatch with what was in the initial server-side render. )
- Moving away from the dynamically-generated ID to a static ID based on the Storyblok UUID …

ADAPT-3103: Updated unique ID for embed cards, to avoid error.

---

src/components/page-types/basicPage.js
src/components/partials/seo.js

- Removes canonical metatag when noindex metatag is present.
- Before end of sprint.
- 6/10
- Can have a negative impact on page SEO if not resolved.
1. Go to /test/nathan/no-index-test
2. Validate that noindex tag is present, and that canonical metatag does not appear.
3. Go to another page, like the homepage. Validate that the canonical metatag still appears as expected. 
- https://stanfordits.atlassian.net/browse/ADAPT-3106
- https://www.searchenginejournal.com/google-dont-mix-noindex-relcanonical/262607/

ADAPT-3106: Make noindex and canonical tags mutually exclusive.

---

netlify.toml

- Note that the ticket includes several other sites - this PR only provides a solution for saa_alumni.
- Sets header preventing site from being embedded in iframes. (With the exception of the /editor page).
- Before end of current sprint. 
- 6/10? This helps to improve site security and ensure site is not embedded by unauthorized actors. 
This can only be validated on Netlify.
1. Visit any page on the Netlify Preview site.
2. Open the browser dev tools, click the Network tab, and click the entry for the current page request.
3. Look for the "x-frame-options" header in the Response Headers, confirm it says "Deny".
4. As an additional validation step, you can also create an HTML file with an iframe embed in it: `<iframe src="https://deploy-preview-156--stanford-alumni.netlify.app/editor" …

ADAPT-3305: Added x-frame-options header.

---

netlify.toml

- Adding basic auth headers to user-guide pages
1. Navigate to 
3. Verify that the credentials are required and allow access to all /user-guide/* pages

ADAPT-2770 | @mattanglin | Adds basic auth to the user-guide

---

src/components/page-types/TripPage/TripPage.jsx
src/components/page-types/TripPage/TripPageFacultySection.jsx
src/components/page-types/TripPage/TripPageFacultySection.styles.js
src/components/page-types/TripPage/TripPageOverviewSection.styles.js

This PR is based off of #195 and thus it includes the changeset from that PR as well. This PR will be rebased once #195 has been merged into `dev`.
- Trip Page Faculty Leaders Section
- I added `basicCardHorizontal` for the faculty leader cards which needed to be added to components allow-list for the grid.
- There's an additional header component added with no content to create spacing between the faculty cards and the poster. Maybe we want to create a simple spacing component?
- I believe we'll need a new gradient overlay treatment for the poster component.
- end of sprint
1. Navigate to https://deploy-preview-196--stanford-alumni-uat.netlify.app/travel-study/trips/botswana-south-africa-and-zambia/#trip-faculty-leaders-section
3. Verify styling and display of faculty leaders section

ADAPT-3258 | @mattanglin | trip page faculty section

---

src/components/composite/alert.js

Fix alert component to be hidden by default until locally stored dismissal checked to prevent server rendering
- ASP
- 
1. Check that alerts only display on client (not in page source) when not already dismissed

nojira | @mattanglin | these alerts are just wrong

---

src/utilities/filterTrips.js

- Trip duration filter should calculate inclusive # of days, eg, if trip is from May 1-2, it should have a trip duration of 2 days and not 1 day.
https://stanfordits.atlassian.net/browse/ADAPT-4208
1. GO to https://deploy-preview-265--stanford-alumni.netlify.app/travel-study/destinations/?page=1&trip-duration=15-
2. Check this trip that's from May 10 to 24, shows up under the "15+ days" duration filter, instead of the 10-14 days filter
- Other …

ADAPT-4208: Add 1 day to filter trip duration since we're doing inclusive # of days

---

src/components/composite/HeroImage/HeroImage.styles.js
src/components/embed/giveGabForm.js
src/components/page-types/formPage/formPage.js
src/components/page-types/formPage/tripNotifyMe.js
src/tailwind/plugins/theme/colors.js

- Tagging @sherakama for retro review 😄 
- add single column layout option to form theme 
- make form adjustments outlined in ADAPT-4927
- fixup responsive styling
- End of Sprint Q (retro review)
1. Login as `zguan`
2. Review the designs of the following pages
- [`/travel-study/italy-notify-me-form/`](https://deploy-preview-337--stanford-alumni.netlify.app/travel-study/italy-notify-me-form/)
- [`/travel-study/additional-payment-form`](https://deploy-preview-337--stanford-alumni.netlify.app/travel-study/additional-payment-form/)
- [`/travel-study/custom-journeys-form`](https://deploy-preview-337--stanford-alumni.netlify.app/travel-study/custom-journeys-form/)
Refer to [Drea's blue text notes and form page skin section.](https://www.figma.com/file/ZzuzKL805DOjPyT31ICc0c/Travel-Study-Microsi …

ADAPT-4414 | @rebeccahongsf | add single column layout option to form theme

---

src/api/auth/profile.js
src/components/composite/Alert/globalAlert.js
src/components/navigation/accountLinks.js
src/contexts/AuthContext.js

- Adds a try/catch to fetch profile information from the FullGG endpoint by way of two different oauth tokens
- Adds handling to when a user is able to authenticate with Stanford Pass but not with the API
- Updates the User login links to the ones we had discussed earlier today.
- EOD June 6
- Lowish
1. Review code
2. Navigate to the preview build and log in with a test user
3. Review links in the User utility nav
4. Pull down the code to your local
5. Update your vault variables `npm run vault:local` (Backup your current ones)
6. Change the value of MEGAPROFILE_URL to something invalid
7. Spin up the site `npm run dev` 
8. Login and see the failed login notice in the top

Support Mulesoft and Keycloak oauth providers for FullGG

---

src/components/page-types/registrationFormPage/tripTravelerCard.js
src/components/simple/heroIcon.js

- add small plus and minus icon
- update icon style on traveler card
1. Navigate to [`travel-study/italy/registration`](https://deploy-preview-395--stanford-alumni.netlify.app/travel-study/italy/registration)
2. Confirm that the icons are identical in size and the hocus works for traveler card buttons
3. Review code
- ADAPT-5012

ADAPT-5012 | @rebeccahongsf | add small plus and minus icon, update icon style on traveler card

---

src/components/page-types/registrationFormPage/registrationFormPage.js

-  add conditional check for pre/post ext dates
1. Navigate to `travel-study/destinations/dutch-2022/register`
2. Login and fill out the form
3. Verify in admin UI that the dates are being passed in correctly
4. Verify that the confirmation email does display invalid dates
- ADAPT-5285

ADAPT-5285 | @rebeccahongsf | add conditional check for pre/post ext dates

---

src/components/composite/itineraryItem.js

- The last item in the itinerary should display accommodation and or meals if they are entered
- Soon
1. Go to https://deploy-preview-460--stanford-alumni.netlify.app/travel-study/destinations/everest-2022/#itinerary-section
2. Scroll to the last itinerary step, the meal should be displayed
You can compare to currently on dev, it doesn't display the meals on the last day
https://dev--stanford-alumni.netlify.app/travel-study/destinations/everest-2022/#itinerary-section
3. Look at code
- Other PRs
- [AMP …

ADAPT-5375 | Itinerary last item should display accommodation and meals

---

src/api/travel-study/index.js
src/api/travel-study/reg/post-extension.js
src/api/travel-study/reg/pre-extension.js
src/components/cta/SAALinkButton.jsx
src/components/embed/dynaScript.js
src/components/page-types/TripPage/TripPageOverviewSection.jsx
src/components/page-types/TripPage/TripPageOverviewSection.styles.js
src/components/page-types/TripPage/TripPagePricingSection.jsx
src/components/page-types/TripPage/TripPageSectionNav.jsx
src/components/page-types/TripPage/TripPageSectionNav.styles.js
src/components/page-types/registrationFormPage/interstitialPage.js
src/components/page-types/registrationFormPage/registrationFormPage.js
src/components/page-types/registrationFormPage/tripTravelerList.js
src/styles/forms.css

[Batches requested fixes from TSGG](https://docs.google.com/spreadsheets/d/1pCukzFMRrFqoeMzej08lKv_FKgbcu-umrTOK8ss7mxI/edit#gid=1871597942)
- Open Reserve form link in new tab (no additional changes to SB needed)
- Update Added Travelers empty state text on interstitial page
- Remove `Trip: Registration` header from registration form
- Increase "Add Traveler" link on GG registration form payment page
- Resolve cancellation policy anchor link over-scroll
- Update "Explore More Destinations" from title casing to sentence casing ("Explore more destinations") on Notify me confirmation page
- Update intro text on interstitial page
- Update trip deposits to display as USD currency values
- Sooner the better please! Thank you 🙏 
2. Navigate to …

ADAPT-5355 and ADAPT-5360s series | @rebeccahongsf |  bulk tsgg updates

---

src/styles/forms.css

-  With the new GG checked style update for the Other field, we need to further specify radio button styling
- asap for UAT
1. Navigate to the Italy Test trip registration
2. Continue onto registration form
3. Fill out the Other text field(s)
4. Verify that the style correctly displays. There should be no additional circle to the left of the Other textfield.
5. Review code
- ADAPT-5426

ADAPT-5426 | @rebeccahongsf | further specify radio button styling

---

src/styles/forms.css

- since the primary registrant/travel must always attend the trip, hide remove btn option specifically for the primary reg
- Friday morning, 10/14 
1. Login as zguan
2. Navigate to `travel-study/destinations/italy-test/register`
3. Select an additional traveler or two
4. Continue to through the form
5. On the payment summary page, confirm that the `remove` text doesn't display for the primary registrant
6. Edit the primary registrant and confirm that the `Remove traveler` link doesn't display
7. Go back to the payment summary page and edit an additional traveler
8. Confirm that the `remove traveler` link displays.
9. Review code 👾

NOJIRA | @rebeccahongsf | hide remove btn for primary reg

---

src/styles/forms.css

- fixup remove btn styles
- asap
1. Login as zguan
2. Navigate to [`travel-study/destinations/italy-test/register`](https://deploy-preview-488--stanford-alumni.netlify.app/travel-study/destinations/italy-test/register)
3. Select an additional traveler or two
4. Continue to through the form
5. On the payment summary page, confirm that the `remove` text doesn't display for the primary registrant
6. Edit the primary registrant and confirm that the `Remove traveler` link doesn't display
7. Go back to the payment summary page and edit an additional traveler
8. Confirm that the `remove traveler` link displays.
9. Review code 👾

NOJIRA | @rebeccahongsf | fixup remove btn styles

---

gatsby-node.js

- exclude membershipFormPage from component
2. Navigate to [http://localhost:8000/membership/register/](http://localhost:8000/membership/register/)
3. Verify that your interstitial page displays
4. Navigate to [http://localhost:8000/membership/register/form](http://localhost:8000/membership/register/form)
5. Verify that the membership form page displays
- ADAPTSM-42

ADAPTSM-42 | @rebeccahongsf | fixup gatsby node config

---

gatsby-node.js
src/components/components.js
src/components/page-types/membershipFormPage/membershipFormPage.js
src/components/page-types/membershipFormPage/relatedContactSelection.js
src/components/page-types/membershipFormPage/relatedContactSelection.styles.js
src/templates/storyblok-entry.js

- scaffold the related contact selection interstitial page
- tweak membership styling
Note: Additional styling and adjustments to the data flow will be made in[ ADAPTSM-54](https://stanfordits.atlassian.net/browse/ADAPTSM-54) and [ADAPTSM-56](https://stanfordits.atlassian.net/browse/ADAPTSM-56)
1. Navigate to [`membership/register/related-contacts`](https://deploy-preview-533--stanford-alumni.netlify.app/membership/register/related-contacts)
3. Verify that the user's relationship(s) display. (Currently, there is only one relationship)
4. Confirm that the Next button displays as disabled by default and the user cannot continue to the form page.
5. Review code 👾 
- [ADAPTSM-55](https://stanfordits.atlassian.net/browse/ADAPTSM-55)
- …

ADAPTSM-55 | @rebeccahongsf | create related contact selection interstitial page

---

gatsby-config.js
src/components/components.js
src/components/page-types/membershipFormPage/membershipInfoText.js
src/components/page-types/membershipFormPage/membershipInformation.js
src/components/page-types/membershipFormPage/membershipInformation.styles.js
src/components/page-types/membershipFormPage/relatedContactSelection.js
src/components/page-types/membershipFormPage/typeOfRegistrant.js

- add membership info into an editable block 
- add digital membership card into an editable block 
**NOTE: Additional styling will be done within [ADAPTSM-43](https://stanfordits.atlassian.net/browse/ADAPTSM-43)**
- when convenient
1. Review [StoryBlok content authoring env for Membership Reg page](https://app.storyblok.com/#/me/spaces/184821/stories/0/0/224400868)
2. Navigate to [`/membership/global-membership-information/`](https://deploy-preview-538--stanford-alumni.netlify.app/membership/global-membership-information/) to see the preview
3. Navigate to [`/membership/register`](https://deploy-preview-538--stanford-alumni.netlify.app/membership/register) to see the membership intro info and membership card info
4. Review code 👾 
- ADAPTSM-25
[ADAPTSM-43]: …

ADAPTSM-25 | @rebeccahongsf | add membership info blocks

---

gatsby-config.js

- [ADAPTSM-40](https://stanfordits.atlassian.net/browse/ADAPTSM-40): DEV | Confirm that the membership pages are excluded from site-map.xml
- Membership form pages included in the sitemap prior to this update:
- See https://deploy-preview-571--stanford-alumni.netlify.app/sitemap/sitemap-0.xml for updated sitemap
1. Review preview sitemap at https://deploy-preview-571--stanford-alumni.netlify.app/sitemap/sitemap-0.xml and confirm membership pages we want removed have been removed
2. Review code 🔢 
[ADAPTSM-40]: https://stanfordits.atlassian.net/browse/ADAPTSM-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADAPTSM-40 | @jdwjdwjdw | exclude membership pages from sitemap

---

src/components/page-types/membershipFormPage/MembershipCard.styles.js
src/components/page-types/membershipFormPage/membershipCard.js
src/components/page-types/membershipFormPage/membershipPaymentCard.js
src/components/page-types/membershipFormPage/relatedContactSelection.js
src/components/page-types/membershipFormPage/typeOfRegistrant.js
src/contexts/FormContext.js

- update select ux 
- update membership card styling
- add digitalName
1. Navigate to [`membership/register`](https://deploy-preview-568--stanford-alumni.netlify.app/membership/register)
2. Verify that you are able to select between the two type of registrants without having to unselect one before selecting the other
3. Navigate to [`membership/register/related-contacts`](https://deploy-preview-568--stanford-alumni.netlify.app/membership/register/related-contacts)
4. Verify that the new contact styling still appears as expected
5. Select a registrant and continue to the form
6. Confirm that the digital name now displays:
7. Review code (confirm that disable styling has been removed) 👾 
- ADAPTSM-118
- ADAPTSM-120

ADAPTSM-118 | @rebeccahongsf | update select ux and add digitalName

---

src/components/page-types/membershipFormPage/membershipFormPage.js
src/components/page-types/membershipFormPage/membershipFormPage.styles.js
src/components/page-types/membershipFormPage/membershipInstallmentsForm.js

- add responsive styling for membership forms
1. Login as `zguan`
2. Navigate to [`/membership/register`](https://deploy-preview-581--stanford-alumni.netlify.app/membership/register)
3. Select `Myself` and `One time payment` then continue to form
4. Use inspect browser tool to verify the different breakpoints (xxl, xl, lg, md, sm, xs) with the [Figma mock under components and the GG Payment Pages](https://www.figma.com/file/BfEeWa39C6xT6muvdkBXsw/Membership-2022%2F23?node-id=1200%3A151628&t=kiPibX5XGabdV3Rj-1)
5. Navigate back to [`/membership/register`](https://deploy-preview-581--stanford-alumni.netlify.app/membership/register)
6. Select `Myself` and `Installments` then continue to form
7. Use inspect browser tool to verify the different breakpoints (xxl, xl, lg, md, sm, …

ADAPTSM-36 | @rebeccahongsf | add responsive styling for membership form pages

---

src/assets/check-mark.svg
src/styles/forms.css

- [ADAPTSM-28](https://stanfordits.atlassian.net/browse/ADAPTSM-28): THEME | Style GG form fields
- Additional changes to the Recipient Display name will be completed in [ADAPTSM-146](https://stanfordits.atlassian.net/browse/ADAPTSM-146)
- The terms and conditions checkbox currently looks unstyled, but that should be corrected once the givegab team updates the form structure. Once they have done that, we will review for additional styling in https://stanfordits.atlassian.net/browse/ADAPTSM-145.
1. Check out this branch or view preview at https://deploy-preview-574--stanford-alumni.netlify.app
2. Navigate to [/membership/register](https://deploy-preview-574--stanford-alumni.netlify.app/membership/register) and login as `zguan`
3. Select `Myself` > `Pay in full` > `Select …

ADAPTSM-28 | @jdwjdwjdw | style gg form fields

---

src/components/page-types/membershipFormPage/MembershipCard.styles.js
src/components/page-types/membershipFormPage/membershipCard.js
src/components/page-types/membershipFormPage/membershipFormPage.js
src/components/page-types/membershipFormPage/membershipFormPage.styles.js
src/components/page-types/membershipFormPage/membershipPaymentCard.js
src/components/page-types/membershipFormPage/membershipPaymentCard.styles.js
src/styles/forms.css

- ADAPTSM-69 | fixup button accessibility upon submission
-  ADAPTSM-164 | replace article wrapper with div
- ADAPTSM-165 | fixup headings
- ADAPTSM-166 | fixup terms and conditions
- retro review when possible — I'll most likely roll this into the `membership` branch so I can continue on with the request theming feedback
1. Navigate to [`membership/register`](https://deploy-preview-604--stanford-alumni.netlify.app/membership/register)
2. Inspect the headings structure
```
H1: Page Title
H2: Who do you wish to purchase payment for?
H3: Myself, Someone else
H2: Payment options
H3: Full Payment, Installments
```
3. Inspect Membership Card(s) and confirm that the wrapper around button is a `<div>`
4. Proceed to the form and confirm that the Terms & Conditions appear like the Figma
5. Submit …

ADAPTSM-69 | @rebeccahonsf | accessibility fixup

---

src/components/page-types/membershipFormPage/MembershipCard.styles.js
src/components/page-types/membershipFormPage/membershipCard.js
src/components/page-types/membershipFormPage/membershipFormPage.js
src/utilities/mocks/fullgg.js

- check the membership API to see if the user has an existing memebrship. If so, do not allow them to proceed with purchasing.
- EOD Friday, 4/14
2. Add `MEGAPROFILE_MOCK = 'true'` to your `.env`
3. Spin up your local
4. Navigate to `/api/auth/profile`
5. Confirm that the membership mock data appears
*Note: If you encounter a data error (e.g. `Cannot read properties of undefined (reading 'data')`), go to your local `profile.js` file and comment out all lines related to `contact`. That should resolve the issue.
6. Navigate to `/membership/register`
7. Login and verify that you are able to select between the two memberships
8. On your local, navigate to `fullgg.js` and comment out the empty membership array. Comment in the Alumni data
9. Navigate to …

ADAPTSM-169 | @rebeccahongsf | add digital card membership check

---

src/api/auth/profile.js
src/components/cards/membershipCard.js
src/utilities/mocks/fullgg.js

- configure memberships endpoint
- asap 🙏 
1. Navigate to [`/membership/saacard` netlify preview](https://deploy-preview-646--stanford-alumni.netlify.app/membership/saacard/)
3. Confirm that a sample card appears
4. Check out this branch
5. Add `MEGAPROFILE_MOCK = 'true'` to your `.env`
6. Spin up your local
7. Navigate to `/api/auth/profile`
8. Confirm that the membership mock data appears
*Note: If you encounter a data error (e.g. `Cannot read properties of undefined (reading 'data')`), go to your local `profile.js` file and comment out all lines related to `contact`. That should resolve the issue.
9. Navigate to `/membership/saacard`
10. Login and verify that the red [Alumni card](https://www.figma.com/file/c8Zv388RgBwDcSPtBTZhc1/Digital-Membership-Cards?node-id=0%3A …

ADAPTSM-158 | @rebeccahongsf | configure memberships endpoint

---

src/components/page-types/membershipFormPage/membershipFullPaymentForm.js

- set appeal code to always pass into adc val
- retroreview
1. Login as zguan
2. Navigate to `/membership/register?appeal_code=randomcode`
3. Change the promo code to anything you'd like
4. Proceed to the Myself, full payment form
5. Inspect browser, navigate to console tab, and input `window.su_appeal_code`
6. Confirm that this matches the promo code you entered in
7. Navigate back to `/membership/register?appeal_code=randomcode`
8. Change the promo code to anything you'd like
9. Proceed to the someone else form
10. Inspect browser, navigate to console tab, and input `window.su_appeal_code`
11. Confirm that this matches the promo code you entered in
12. Review code 🤖 
- ADAPTSM-67

ADAPTSM-67 | @rebeccahongsf | set appeal code to always pass into adc val

---

src/components/page-types/membershipFormPage/membershipInstallmentsForm.js
src/styles/forms.css

- [ADAPTSM-176](https://stanfordits.atlassian.net/browse/ADAPTSM-176): DEV | Form theme updates
- All Optional help text fields on the membership forms should display consistently below the label and above the text field.
- Can be seen by going to `Someone else` > `Add new contact`
- On the installments form, first page within the membership options table, there should be a space between “annual” and Membership
1. Check out this branch or view preview
2. Login as `carinaw` and navigate to `/membership/register`
3. Select `Someone else` > `Add new contact`, and confirm the captions are being displayed below the label and above the text field
4. Navigate back to `/membership/register`, and select `Myself` > `Pay in installments`
5. Confirm there is spacing between `5 …

ADAPTSM-176 | @jdwjdwjdw | Form theme updates

---

netlify.toml

- remove basic auth from membership form and card pages
- asap
1. Navigate to [`/membership/join`](https://deploy-preview-675--stanford-alumni.netlify.app/membership/join) and [`/membership/saacard`](https://deploy-preview-675--stanford-alumni.netlify.app/membership/saacard)
2. Verify that you are able to access the page without basic auth
3. Review code
- ADAPTSM-74

ADAPTSM-74 | @rebeccahongsf | remove basic auth from membership form and card pages

---

src/components/navigation/MegaMenu/megaMenuLink.styles.js
src/components/navigation/MegaMenu/megaMenuLinkGroup.js
src/components/navigation/MegaMenu/megaMenuPanel.js
src/components/navigation/MegaMenu/megaMenuPanel.styles.js

Note: #714 was merged into megamenu for review. This is a cherry-picked version for dev
- fix bouncing secondary link
- add collapse animation
- add box shadow/gradient to menu panel
- TBD, awaiting further possible feedback from business
1. Navigate to https://deploy-preview-716--stanford-alumni.netlify.app/
2. Verify that the secondary links (within the dropdown/menu panel) do not bounce (compare to [megamenu dev](https://megamenu--stanford-alumni.netlify.app/))
3. Verify that there is now a close animation
4. Verify that there is a box shadow at the bottom of the menu panel (see [`about/jobs`](https://deploy-preview-716--stanford-alumni.netlify.app/about/jobs/) for a clear example) and a "box shadow" within the panel
5. Determine if "box shadow" implementation within the panel makes …

DS-98 | @rebeccahongsf | fixup qa bugs (#714)

---

src/styles/forms.css

- further specify styling to not impact mobile payment not available message
- asap
1. Navigate to https://deploy-preview-727--stanford-alumni.netlify.app/travel-study/destinations/finland-2022/finland-reg-form
2. Verify that the Mobile Payments are not available message does not have a white box
Note: I find that using Chrome where you are logged into your Stanford Account will disable GPay, allow this message to show
3. Review code
- DS-387

DS-387 | @rebeccahongsf | fixup mobile payment not available

---

src/utilities/dataSource.js

- Fixes the hero gradient for larger breakpoints
2. Navigate to or create a page with a hero component that has an image.
3. Change the Hero Gradient to one of the choices other than Default: Brick, Palo Alto Dark, or White.
4. Verify that:
At the xs breakpoint, the gradient starts at the top with the specified color at 30% opacity and then goes to #181D1C 100% opacity at the bottom.
For all widths larger than xs, the gradient starts at #181D1C 0% opacity at the top and then goes to the specified color 100% opacity at the bottom.
- JIRA ticket: HOM-1
- @William-Misiaszek

Adds gradients for breakpoints larger than xs

---

src/components/page-types/membershipFormPage/membershipFormPage.styles.js

- fix font sizing for promo code input
1. Navigate to [dev preview](https://deploy-preview-803--stanford-alumni.netlify.app/membership/join?appeal_code=12345)
2. Verify that the promo code appears in normal font size (compared to [PROD](https://alumni.stanford.edu/membership/join?appeal_code=45243))
3. Review code
- DS-525

DS-525 | @rebeccahongsf | fix font sizing for promo code input

---

src/utilities/sbLink.js

- Remove IDs from links
- Storyblok passes the UID in the link data's id key (WHY!? They already include it in the `_uid` key!) which we don't want to use as the link's actual id attribute value
- I didn't see any other duplicate ID issues outside of links (but will check after the next re-scan)
- High
1. Use the [deploy preview](https://deploy-preview-817--stanford-alumni.netlify.app/)
2. Go to any page
3. Inspect any internal link (e.g. in the main nav)
4. Verify that it doesn't have an id attribute
5. For bonus points, run the page through the SiteImprove browser plugin to make sure it doesn't pick up duplicate IDs
- DS-582

DS-582 | @ericbakenhus | Remove duplicate IDs

---

src/utilities/richTextRenderer.js

- Prevents empty links in the WYSIWYG editor from rendering (a11y issue)
- Low
1. See an example of an empty link on the [newsletters page on the dev site](https://dev--stanford-alumni.netlify.app/resources/newsletters/):
2. Go the [newsletters page on the deploy preview](https://deploy-preview-819--stanford-alumni.netlify.app/resources/newsletters/)
3. Verify that the empty link no longer appears:
- DS-583

DS-583 | @ericbakenhus | Don't render empty links

---

src/components/page-types/membershipFormPage/membershipFormPage.js
src/components/page-types/membershipFormPage/relatedContactSelection.js
src/components/page-types/registrationFormPage/interstitialPage.js
src/utilities/userProfile.js

- Rework GiveGab Prefill data for T/S and Membership forms
- 3
2. Navigate to `/travel-study/destinations/china-2024/reserve/form` (or any other T/S form) and make sure everything works as expected
3. Navigate to `/membership/join/form` and make sure `Membership` form works as expected
4. Make sure everything else still works as expected
P.S. I didn't create a new object for the `related contacts` because we are not using the same fields for the `related contacts` object in T/S and Membership forms.

DS-134: Rework GiveGab Prefill data for T/S and Membership forms

---

cypress/e2e/1-perks/online-database.cy.ts
netlify/edge-functions/protected-content.js

- Passes any search string and/or hash when auth is triggered when trying to visit a protected page
- ASAP
- High
1. Use the [deploy preview](https://deploy-preview-822--stanford-alumni.netlify.app/)
2. Without being logged in, navigate to [/membership/join?appeal_code=45243&test=test#su-promocode](https://deploy-preview-822--stanford-alumni.netlify.app/membership/join?appeal_code=45243&test=test#su-promocode)
3. Log in
4. Verify that the final destination URL contains the search string and hash (`test` and the hash won't actually do anything, just testing that they make it through)
5. Verify that the Promo code input is pre-filled with `45243`
- DS-615
- DS-584

DS-615 | @ericbakenhus | Pass search and hash when triggering auth on protected content

---

src/components/identity/localFooter.js
src/components/navigation/linkGroup.js

- There is a new footer in the [prod Alumni](https://alumni.stanford.edu/) that omits expected content causing several empty elements to render
- Hides certain local footer elements if left empty in Storyblok
- NOTE: This is just a quick band aid to handle the a11y issues with the new local footer content and is not meant to suggest a long-term strategy to handle these types of content changes 😅 
- ASAP
- High
1. Use the [deploy preview](https://deploy-preview-839--stanford-alumni.netlify.app/)
2. Navigate to the [home page](https://deploy-preview-839--stanford-alumni.netlify.app/) (the dev home page has been altered to use a local footer that is similar to the current prod local footer)
3. Verify the spacing and layout looks similar to the [current prod local …

DS-644 | @ericbakenhus | Hide footer elements if missing in Storyblok

---

src/components/page-types/associatesDirectoryPage/Directory/AssociateList.jsx
src/components/simple/linkList.js

- Hides a couple `ul`s if they're empty.
- Whenever
- Low
1. Check out this branch or use the [deploy preview](https://deploy-preview-842--stanford-alumni.netlify.app/)
2. Navigate to [/groups/identities/](https://deploy-preview-842--stanford-alumni.netlify.app/groups/identities/)
3. Verify there aren't a bunch of empty `ul`s below "Shared Identity" (you can use an a11y tool to check for 1.3.1 issues)
For example (dev site on left, deploy preview on right):
4. Look at code for the associate list (since we can't really test it easily) and make sure the [page itself](https://deploy-preview-842--stanford-alumni.netlify.app/stanford-associates/directory/) still functions correctly
- DS-654

DS-654 | @ericbakenhus | Hide empty uls

---

netlify/functions/handle-deploy-background.ts
package-lock.json
package.json
src/types/storyblok/api/SBWebhookType.ts
src/utilities/mergeEventOverrides.js

Note: Merging this up to dev/main since it will fully replace the existing legacy webhooks in Storyblok.
- Create new background function to handle Storyblok webhook events (everything that the current legacy webhooks do + event story handling: pub, unpub, delete, etc.)
- Low
1. Open this [deploy preview's function logs in Netlify](https://app.netlify.com/sites/stanford-alumni/logs/functions/handle-deploy-background?scope=deploypreview:851)
2. Trigger any/all of the following events in the Dev space in Storyblok: 
- publish synchronized event (upserts to the dev Algolia index)
- unpublish synchronized event (deletes from dev algolia index)
- publish other story (triggers Netlify deploy of the Events Discovery branch)
- unpublish other story (triggers Netlify deploy of the …

DS-683, DS-692, DS-693 | @ericbakenhus | Webhook background function

---

src/components/navigation/MegaMenu/megaMenu.js

- This PR just adds `justify-end` class to mega menu component 
- 5
2. Open `test-furkan-travel-study-homepage` in Storyblok and make sure that mega menu component works as expected
3. Open `/travel-study/global-components/global-header/default-travel-study-global-header-test-furkan` and make sure that mega menu component can be configured as expected and works as expected
4. Make sure that `globalHeader` block has the option to select `saaMainNav` or `megaMenu` and works as expected for both of the menu options.

DS-662: Add Mega Menu option to sub pages on Alumni Homesite

---

src/components/events-discovery/components/Event/EventContent.jsx

- Handle the edge case where timezones are different but the offsets are the same (thanks Arizona)
- Retro
- Low
3. Create/edit an event so that the timezone is `America/Phoenix`
4. Verify you see something like this for that event (assuming you're in PDT currently):
- DS-793

DS-793 | @ericbakenhus | Handle when different timezones with the same offset

---

src/components/navigation/MegaMenu/megaMenuPanel.js
src/components/navigation/MegaMenu/megaMenuPanel.styles.js

- Does exact string matching instead of partial for setting active links in the mega menu
- EOW (Aug 2)
- Normal
1. Navigate to https://alumni.stanford.edu/career-connections/students
2. See the mega menu top level links light up for more than one section
3. This is due to the nav items with the url string `students` matching in `/career-connections/students`
4. Navigate to the [preview build](https://deploy-preview-897--stanford-alumni.netlify.app/career-connections/students)
5. Validate that only one mega menu top level is highlighted

Bug: False matching of active URLs.

---

src/components/events-discovery/components/Facets/MobileFacetList.jsx

- Show the checkboxes on mobile filters and use them for active state
- Soon
- Medium
3. Verify the checkboxes are now visible on mobile filter refinement lists and work as expected
- DS-800

DS-800 | @ericbakenhus | Adjust mobile filter active, hover, focus styles

---

src/components/events-discovery/components/LocationFilter/LocationFilter.jsx

- Add reset button to top-level location filter (resets all location filters)
- Retro
- Medium
3. Verify that a reset button appears for the top-level location filter when any location-based filter is active
4. Verify that the reset button resets all location-based filters
- DS-800

DS-800 | @ericbakenhus | Add location reset button

---

src/components/content-types/synchronized-event/SynchronizedEventCard.jsx
src/components/events-discovery/components/Event/EventContent.jsx

- Stretches the event card link over the entire card
- Soon-ish/retro
- Medium
2. Navigate to [/test-eric/test-basic/](https://deploy-preview-959--stanford-alumni.netlify.app/test-eric/test-basic/)
3. Verify that each card's link covers the entire card
4. Verify that there are no time zone selects on any card
- DS-735

DS-735 | @ericbakenhus | Stretch link for event cards

---

src/components/events-discovery/components/NoResults/NoResultsComponent.jsx
src/components/events-discovery/components/Pagination/Pagination.jsx
src/components/events-discovery/components/StatusHeader/StatusHeader.jsx

- Scroll to top of results when paging though events
- Now/retro
- High
3. Click through the pagination nav
4. Verify you are scrolled to the top of the results
5. Verify focus is moved to the results heading (results count)

Nojira | @ericbakenhus | Scroll to heading on event pagination change

---

netlify/functions/event-import-background.mts

- Removes the draft version of any events that are published with changes (will appear in both published and draft requests)
- Splits out `isPublished` to prevent it from appearing in other systems
- 🤷 
- Medium(?)
2. Maybe ping the deploy preview background function with Postman and watch the logs (feel free to set `run` to `test` in vaut if you don't want it to make changes in the dev SB space; doesn't really matter either way though)
- https://deploy-preview-981--stanford-alumni.netlify.app/webhook/sb/event-import?secret=[secret-here]

Nojira | @ericbakenhus | Remove draft versions of published events

---

src/components/events-discovery/components/Event/EventContent.jsx

- Handle edge case where changing an event's displayed time zone to the user's local time zone crosses a date boundary
- Switch the check for single/multi day events to look only at the event time zone and not the selected time zone
- Display a +/- 1 day flag when a time crosses into a different day
- Soon
- Medium
3. Change your system's time zone as needed
4. Swap single day event time zones to cause start or end time to cross into a different day
5. See the new +/- 1 day flag
For example:
- DS-998

DS-998 | @ericbakenhus | Handle time zone changes that cross day boundaries
